import type { ExploreItem } from "../components/continue-exploring";

export type ArchNode = { label: string; sub?: string } | { group: string[]; details?: string[] };
export type DeepDive = { eyebrow: string; title: string; body: string[]; list?: string[]; flow?: string[]; flowLabel?: string; split?: { title: string; steps: string[] }[]; link?: { label: string; to: string }; tone?: "light" | "muted" };
export type CaseStudy = {
  slug: string;
  crumb: string;
  category: string;
  eyebrow: string;
  title: string;
  heroDescription: string;
  cardProblem: string;
  cardTransformation: string;
  visual: "hero" | "digitalization" | "modernization" | "capacity" | "ai" | "trackTrace" | "engineering";
  metaTitle: string;
  metaDescription: string;
  contextTitle: string;
  context: [string, string][];
  challengeTitle: string;
  challengeBody: string;
  challenges: { title: string; body?: string }[];
  solutionTitle: string;
  solutionBody: string;
  capabilities: string[];
  architecture: { title: string; caption: string; flow: ArchNode[]; aside?: { title: string; items: string[] }; feedback?: string };
  howTitle: string;
  howBody: string;
  steps: string[];
  outcomesLabel: string;
  outcomes: string[];
  tags: string[];
  solutionOutcome: { intro: string; outcomes: string[] };
  explore: ExploreItem[];
  ctaTitle: string;
  ctaBody: string;
  cta: string;
  journey?: { title: string; steps: [string, string][] };
  deepDives?: DeepDive[];
  outcomeCards?: [string, string][];
};

const sol = {
  software: { type: "Solution", title: "Software Engineering", body: "Build operational software around requirements that generic systems cannot solve well.", to: "/solutions/software-engineering" },
  dt: { type: "Solution", title: "Digital Transformation", body: "Connect workflows, information and operational systems around the way the organization actually works.", to: "/solutions/digital-transformation" },
  data: { type: "Solution", title: "Data Engineering & Analytics", body: "Build data pipelines and models the business can depend on.", to: "/solutions/data-engineering" },
  cloud: { type: "Solution", title: "Cloud & Platform Engineering", body: "Make software and data platforms easier to release, operate and recover.", to: "/solutions/cloud-platform-engineering" },
  modern: { type: "Solution", title: "Application Modernization", body: "Preserve the business value of critical software while removing the constraint around it.", to: "/solutions/application-modernization" },
  integration: { type: "Solution", title: "API & System Integration", body: "Let systems exchange information reliably instead of relying on manual handoffs.", to: "/solutions/integration" },
  healthcare: { type: "Industry", title: "Healthcare", body: "Explore how connected administrative and operational systems can reduce complexity behind healthcare delivery.", to: "/industries/healthcare" },
  tech: { type: "Industry", title: "Technology & IT Services", body: "Strengthen delivery around engineering environments, platforms and client commitments.", to: "/industries/technology-it-services" },
} satisfies Record<string, ExploreItem>;

export const caseStudies: CaseStudy[] = [
  {
    slug: "digital-brokerage-platform", crumb: "Digital Brokerage Platform", category: "Fintech · Product & Platform Engineering", eyebrow: "Case study · Fintech platform engineering", visual: "hero",
    title: "Building a connected digital stock brokering platform",
    heroDescription: "A digital investment and trading ecosystem connecting client onboarding, secure identity, fund management, financial data, order workflows, portfolio services and reporting through a scalable integration and cloud architecture.",
    cardProblem: "A modern investment platform needed to connect customer onboarding, identity, payments, financial data, trading, portfolio services and reporting across multiple internal and external systems.",
    cardTransformation: "A unified digital brokerage ecosystem brought the customer journey together through secure identity, cloud services, integration middleware, event-driven processing and connected investment workflows.",
    metaTitle: "Digital Brokerage Platform Case Study", metaDescription: "A fintech case study covering digital onboarding, secure identity, payments, multi-asset trading, middleware integration, financial data and reporting.",
    contextTitle: "A platform shaped around the complete investment lifecycle.",
    context: [["Business environment", "Digital brokerage and investment services"], ["Customer journey", "Onboarding through investment, trading and reporting"], ["Platform scope", "Web, mobile, APIs, middleware and cloud services"], ["Integration environment", "Financial-data providers, payments, identity/compliance systems, exchanges and internal platforms"]],
    challengeTitle: "A digital brokerage is not one application. It is a connected financial ecosystem.",
    challengeBody: "A customer-facing investment experience depends on many systems working together correctly. Registration and identity connect with compliance workflows, funding with payment infrastructure, market information with multiple data providers, and orders with execution and portfolio records. The platform needed an architecture capable of connecting the entire investment lifecycle while keeping clear boundaries between customer-facing applications, financial services, integrations and operational infrastructure.",
    challenges: [
      { title: "Digital onboarding", body: "Enable customers to progress through registration, verification, account information, bank details, nominee information and account activation through a digital journey." },
      { title: "Secure identity", body: "Provide a consistent authentication and access foundation across web, mobile and backend services." },
      { title: "Integration complexity", body: "Connect payment, market-data, identity/compliance, trading and internal financial systems without exposing that complexity to the customer experience." },
      { title: "Transaction reliability", body: "Support workflows where partial failure, duplicate processing or inconsistent state could create downstream operational issues." },
      { title: "Financial reporting", body: "Transform trading and transaction information into understandable portfolio, P&L and capital-gains views." },
      { title: "Production coordination", body: "Operate and release changes across multiple dependent applications and services without treating each deployment as an isolated change." },
    ],
    solutionTitle: "One digital platform spanning the complete investment journey.",
    solutionBody: "Customer-facing applications, serverless services, asynchronous processing, secure identity, middleware, databases and external integrations supported the journey from account opening to reporting. Integration responsibilities sat behind backend and middleware services, so digital channels worked with a consistent application layer while specialist systems handled identity, payments, financial data, execution, compliance and reporting.",
    capabilities: ["Digital client onboarding", "Secure authentication", "Payments & fund management", "Market & investment data", "Trading workflows", "Financial reporting", "Middleware & APIs", "Cloud & event processing"],
    architecture: {
      title: "A platform built around connected financial capabilities.",
      caption: "Digital brokerage platform: web and mobile channels reach an identity and customer-journey layer, then an API and integration backbone that connects financial data, payments, trading and compliance services to data and reporting, supported by cloud, observability, logging, audit and controlled deployment.",
      flow: [
        { group: ["Web Application", "Mobile Application"] },
        { group: ["Authentication / SSO", "Digital Onboarding", "Profile & Account"] },
        { label: "API / Integration Backbone", sub: "API services · Middleware · Asynchronous processing" },
        { group: ["Financial Data", "Payments", "Trading", "Compliance / Verification"], details: ["Market data · Instrument information · Fundamental data", "Payment providers · Fund management · Transaction confirmation", "Order validation · Execution integration · Trade processing", "Identity verification · KYC-related workflows · Document/eSign services"] },
        { label: "Data & Reporting", sub: "Operational databases · Portfolio / positions · P&L · Capital gains · Transaction reporting" },
      ],
      aside: { title: "Supporting platform layer", items: ["Cloud infrastructure", "Observability", "Logging", "Audit", "CI/CD / controlled deployment"] },
    },
    howTitle: "Customer journey combined with platform engineering.",
    howBody: "Onboarding, funding, investing, trading, portfolio and reporting are carried by identity, APIs, integrations, middleware, serverless processing, databases, observability and production delivery.",
    steps: ["Onboard", "Fund", "Invest", "Trade", "Portfolio", "Report"],
    outcomesLabel: "Documented platform outcomes",
    outcomes: ["Unified digital investment journey", "Centralized identity foundation", "Connected financial ecosystem", "Middleware-based integration", "Asynchronous processing", "Multi-asset capability", "Financial reporting foundation", "Production observability"],
    tags: ["Python", "AWS Lambda", "AWS SAM", "Amazon SQS", "Amazon Cognito", "PostgreSQL / RDS", "Amazon S3", "CloudWatch", "REST APIs", "React / Next.js"],
    solutionOutcome: { intro: "The platform now runs as one connected brokerage journey, from onboarding and funding through trading, positions and reporting, with clear boundaries between the product and the providers behind it.", outcomes: ["A connected customer journey from registration to reporting", "Consistent platform behaviour across onboarding, payments and trading", "Clear integration boundaries around exchanges, data and payment providers", "Structured, asynchronous transaction processing", "Defined reconciliation across funds, orders and positions", "Production observability that shortens troubleshooting", "Provider flexibility through a middleware layer", "A foundation that supports future product growth"] },
    explore: [
      { type: "Industry", title: "Fintech", body: "Explore how product engineering, integrations, cloud platforms and delivery capacity support growing financial-technology products.", to: "/industries/fintech" },
      { type: "Solution", title: "Software Engineering", body: "Build product and platform capabilities around requirements that generic systems cannot solve well.", to: "/solutions/software-engineering" },
      { type: "Solution", title: "API & System Integration", body: "Connect financial products, data providers and operational systems through controlled integration boundaries.", to: "/solutions/integration" },
      { type: "Solution", title: "Cloud & Platform Engineering", body: "Build the platform foundations required to operate, monitor and evolve connected digital services.", to: "/solutions/cloud-platform-engineering" },
      { type: "Insight", title: "Fintech platform modernization", body: "Recognize when product growth starts outrunning the architecture—and modernize the constraint.", to: "/insights/fintech-platform-modernization" },
      { type: "Insight", title: "Fintech API & integration strategy", body: "Connect identity, payments, market data, trading and reporting with explicit state ownership.", to: "/insights/fintech-api-integration-strategy" },
      { type: "Insight", title: "What should a fintech outsource?", body: "Map what to own, extend or delegate without losing accountable product ownership.", to: "/insights/fintech-what-to-outsource" },
      { type: "Insight", title: "Reliable asynchronous fintech workflows", body: "Design retries, idempotency, reconciliation and auditability around critical flows.", to: "/insights/fintech-asynchronous-workflows" },
      { type: "Insight", title: "Fintech data engineering", body: "Trace transactional records through reconciliation, models and management reporting.", to: "/insights/fintech-data-engineering" },
    ],
    ctaTitle: "Where is your product roadmap being constrained by platform complexity?",
    ctaBody: "Bring the engineering bottleneck, integration challenge, onboarding workflow or platform constraint. Start with the product problem before deciding what architecture or delivery model needs to change.",
    cta: "Discuss Your Fintech Platform",
    journey: { title: "The customer journey stays connected from account opening to reporting.", steps: [["Discover", "Customer accesses the digital investment platform."], ["Register", "Account registration begins."], ["Verify", "Identity, account information and required verification workflows are completed."], ["Activate", "The account becomes available after required checks."], ["Add funds", "Customer funds the account through supported digital payment channels."], ["Explore", "Customer accesses market and investment information."], ["Place order", "A trade instruction is created and validated."], ["Execute", "The order is routed through the appropriate execution workflow."], ["Update portfolio", "Positions and holdings reflect completed activity."], ["Report", "Transaction history, P&L and capital-gains information become available."]] },
    outcomeCards: [
      ["Unified digital investment journey", "Onboarding, funding, investment discovery, trading and reporting were brought into one broader digital ecosystem."],
      ["Centralized identity foundation", "Authentication and access workflows supported digital application services through a common identity approach."],
      ["Connected financial ecosystem", "Digital channels could integrate with payment, market-data, verification, execution and internal financial systems."],
      ["Middleware-based integration", "External-system complexity could be separated from customer-facing application logic."],
      ["Asynchronous processing", "Selected work could be decoupled from synchronous customer requests."],
      ["Multi-asset capability", "The platform architecture supported multiple investment categories."],
      ["Financial reporting foundation", "Trading and transaction data could feed portfolio, P&L and capital-gains reporting."],
      ["Production observability", "Logs, audit information and monitoring supported operational troubleshooting."],
    ],
    deepDives: [
      { eyebrow: "Digital client onboarding", title: "Onboarding is a workflow, not a registration form.", body: ["Digital account opening required coordination across identity information, verification, bank details, nominee handling, document workflows and downstream account creation.", "The engineering approach separated onboarding into distinct service responsibilities, allowing individual stages to be developed, deployed, monitored and recovered independently where appropriate."], flow: ["Registration", "Identity / KYC-related information", "Bank verification", "Nominee", "Documents / eSign", "Validation", "Account creation"] },
      { eyebrow: "Serverless & asynchronous engineering", title: "Keep customer-facing requests separate from work that can happen asynchronously.", tone: "muted", body: ["Some onboarding and financial workflows include work that should not block the customer-facing request. Asynchronous processing patterns were used for activities that could be longer-running, event-driven, retried independently or processed outside the synchronous API lifecycle."], flowLabel: "Representative event-driven pattern", flow: ["Customer request", "API / service"], split: [{ title: "Immediate response path", steps: ["Validation", "Response"] }, { title: "Background path", steps: ["Queue", "Processing", "Status / downstream action"] }] },
      { eyebrow: "Reliability principle", title: "Financial workflows need explicit failure states.", body: ["In financial platforms, a later technical failure should not automatically invalidate an earlier valid business outcome. Reliable processing therefore requires deliberate attention to how state is owned, preserved and recovered."], list: ["Status ownership", "Successful-state preservation", "Duplicate prevention", "Retries", "Reconciliation", "Event ordering", "Auditability", "Error handling"] },
      { eyebrow: "Integration architecture", title: "Hide external complexity behind a consistent platform layer.", tone: "muted", body: ["A brokerage platform depends on specialized external systems for authentication, verification, financial data, payments, execution, documents and compliance. Customer-facing applications should not have to understand the specific behaviour of every provider.", "The integration layer normalizes those differences where appropriate and provides controlled interfaces to the rest of the platform."], link: { label: "Read: System integration strategy", to: "/insights/system-integration-strategy" } },
      { eyebrow: "Payments & reconciliation", title: "A payment is not complete when the user presses “Pay.”", body: ["Digital funding requires backend consistency between the external payment state and the internal account state, so each stage is recorded and reconciled rather than assumed."], flow: ["Initiate", "Process", "Confirm", "Credit / reflect", "Record", "Reconcile"] },
      { eyebrow: "Multi-asset investment platform", title: "One platform, multiple investment journeys.", tone: "muted", body: ["The documented platform scope included support across investment categories. Customer-facing channels could present a more unified investment experience while backend services handled product-specific workflows."], list: ["Equities", "Bonds", "ETFs", "Commodities", "Mutual funds"] },
      { eyebrow: "Market & fundamental data", title: "Multiple data sources, one customer experience.", body: ["Market and investment information may originate from several specialized providers. The architecture therefore needs to handle that variety without passing it on to the customer."], list: ["Integrate multiple sources", "Normalize information", "Validate data", "Expose consistent interfaces", "Isolate vendor-specific behaviour", "Support future provider changes"] },
      { eyebrow: "Financial reporting", title: "Transaction data becomes useful when customers can understand it.", tone: "muted", body: ["Reporting depends on consistent processing of transactional information across trading and funding activity."], list: ["Trade-wise P&L", "Realized P&L", "Unrealized P&L", "Capital gains", "Transaction history", "Trading activity", "Portfolio information"] },
      { eyebrow: "Production & release engineering", title: "In an integrated platform, releases are dependency problems as much as code problems.", body: ["Changes across authentication, onboarding, profile, investment products, payment services, shared databases and integration services cannot always be deployed independently. Delivery involved cross-application release coordination and dependency sequencing rather than isolated deployments."], flow: ["Dependency mapping", "Change readiness", "Approval", "Deployment sequencing", "Validation", "Monitoring"] },
      { eyebrow: "Production troubleshooting", title: "Follow the transaction across the system boundary.", tone: "muted", body: ["A financial workflow may fail anywhere along its path. Reliable root-cause analysis requires end-to-end tracing across serverless functions, APIs, databases, third parties and logs rather than debugging one codebase in isolation."], flow: ["Request", "API", "Service", "Queue", "Database", "Third party", "Downstream service"] },
    ],
  },
  {
    slug: "hospital-operations-platform", crumb: "Hospital Operations Platform", category: "Healthcare · Operational software", eyebrow: "Case study · Healthcare operations", visual: "hero",
    title: "Connecting patient intake, appointments, billing and hospital workflows in one operational platform.",
    heroDescription: "A full-stack healthcare application bringing core patient and administrative workflows into a structured digital environment spanning registration, appointments, staff interfaces, billing and prescription management.",
    cardProblem: "Patient registration, scheduling, staff activity, billing and prescription workflows needed structured handling through one dependable application environment.",
    cardTransformation: "A full-stack hospital operations platform connected patient intake, appointments, staff dashboards, billing and prescription management through shared application workflows and APIs.",
    metaTitle: "Hospital Operations Platform", metaDescription: "How a full-stack hospital platform connected patient intake, appointments, staff dashboards, billing and prescriptions through shared workflows and REST APIs.",
    contextTitle: "An application shaped around the hospital's operational journey.",
    context: [["Business environment", "Hospital and healthcare operations"], ["Operational scope", "Patient intake, appointments, staff workflows, billing and prescriptions"], ["Application model", "Full-stack web application supported by REST APIs"], ["Engineering scope", "Frontend, backend, data and operational workflows"]],
    challengeTitle: "Hospital workflows need consistency across every operational handoff.",
    challengeBody: "Patient registration, appointment scheduling, staff activity, billing and prescription workflows each create information that needs to remain connected throughout the operational journey. The project required these activities to operate through a structured application rather than being treated as isolated software functions.",
    challenges: [{ title: "Patient intake", body: "Capture registration and patient information through a structured workflow." }, { title: "Appointment coordination", body: "Support scheduling and appointment-related activity in one application environment." }, { title: "Staff visibility", body: "Provide doctors and operational staff with role-relevant application views." }, { title: "Administrative continuity", body: "Keep billing and prescription-related workflows connected to the wider platform." }],
    solutionTitle: "One application environment for connected hospital operations.",
    solutionBody: "The solution combined application interfaces, REST-based services and structured data handling to support multiple hospital workflows through one operational platform.",
    capabilities: ["Patient registration and intake", "Appointment scheduling", "Doctor and staff dashboards", "Billing workflows", "Prescription management", "REST API integration", "Structured operational records", "Ongoing platform enhancement"],
    architecture: { title: "Workflows connected through one application and API layer.", caption: "Hospital operations platform: users reach a web application whose REST API layer connects four operational domains to a structured data layer, operational dashboards and records.", flow: [{ label: "Patients / Staff" }, { label: "Web Application" }, { label: "REST API Layer" }, { group: ["Patient Records", "Appointments", "Staff Workflows", "Billing & Prescriptions"] }, { label: "Structured Data Layer" }, { label: "Operational Dashboards & Records" }] },
    howTitle: "A patient journey stays connected across operational workflows.",
    howBody: "Registration, scheduling, staff coordination, records and billing move through the same application environment instead of separate tools.",
    steps: ["Register", "Schedule", "Coordinate", "Record", "Bill", "Maintain"],
    outcomesLabel: "Documented operational outcomes",
    outcomes: ["Structured patient registration and intake", "Connected appointment workflows", "Shared doctor and staff application views", "Integrated billing-related processes", "Structured prescription management", "Centralized operational records"],
    tags: ["Java", "Spring Boot", "Python", "Django REST", "React", "Next.js", "REST APIs", "SQL"],
    solutionOutcome: { intro: "Registration, appointments and daily administration now move through one structured application, giving staff a shared operational picture of the hospital's workflow.", outcomes: ["Structured patient registration and intake", "Connected appointment and scheduling workflows", "Shared visibility across administrative staff", "Better continuity between front desk and departments", "Role-based access to operational records", "A stronger foundation for operational reporting"] },
    explore: [{ type: "Insight", title: "Healthcare digital transformation in Africa", body: "Where growing healthcare organizations should begin: the workflows and system gaps behind service delivery.", to: "/insights/healthcare-digital-transformation-africa" }, sol.software, sol.healthcare],
    ctaTitle: "Where are your healthcare workflows becoming difficult to connect?",
    ctaBody: "Bring the process, application constraint or information gap. Start with the operational problem before deciding what technology needs to change.",
    cta: "Discuss a Connected Healthcare Workflow",
  },
  {
    slug: "healthcare-data-processing-pipelines", crumb: "Healthcare Data Pipelines", category: "Healthcare · Data engineering", eyebrow: "Case study · Healthcare data engineering", visual: "digitalization",
    title: "Making complex healthcare data consistent before it reaches downstream workflows.",
    heroDescription: "A healthcare data-processing environment combining rule-based transformation, distributed processing, orchestration, staging and validation around complex billing and operational data.",
    cardProblem: "Large healthcare datasets required repeatable transformation, classification, validation and troubleshooting across multi-stage processing workflows.",
    cardTransformation: "A structured pipeline combined EasyMorph, Databricks, PySpark, Azure Data Factory and SQL Server to standardize data and support reliable downstream processing.",
    metaTitle: "Healthcare Data Processing Pipelines", metaDescription: "A layered healthcare data pipeline using EasyMorph, Databricks, PySpark, Azure Data Factory and SQL Server to standardize, validate and trace billing data.",
    contextTitle: "A pipeline built around the realities of healthcare source data.",
    context: [["Business environment", "Healthcare data and billing operations"], ["Data scope", "Patient, account, facility, service and billing-related information"], ["Processing model", "Multi-stage transformation and validation pipelines"], ["Technology environment", "EasyMorph, Databricks, Azure Data Factory, PySpark and SQL Server"]],
    challengeTitle: "Raw healthcare data rarely arrives ready for downstream use.",
    challengeBody: "Source files contained different identifiers, classifications, formatting patterns and business rules. Processing also needed to remain traceable when records were filtered, omitted or transformed unexpectedly.",
    challenges: [{ title: "Inconsistent source values" }, { title: "Complex healthcare business rules" }, { title: "Large staging datasets" }, { title: "Records requiring traceable troubleshooting" }],
    solutionTitle: "A layered pipeline for transformation, validation and reliable processing.",
    solutionBody: "Rule-based transformation, distributed processing and orchestrated staging were combined so each stage had a clear responsibility and records could be investigated when results looked wrong.",
    capabilities: ["Rule-based EasyMorph transformations", "Scalable Databricks processing", "PySpark transformation logic", "Azure Data Factory orchestration", "SQL Server staging", "Patient and account-field standardization", "Facility and region mapping", "Account-class and service-type transformation", "Data cleansing", "Missing-value handling", "Pipeline troubleshooting", "SQL optimization"],
    architecture: { title: "Each stage owns one part of making the data dependable.", caption: "Healthcare data pipeline: source files pass through EasyMorph rules, Azure Data Factory orchestration, Databricks and PySpark processing, SQL Server staging and validation before reaching downstream billing workflows.", flow: [{ label: "Source Files & Operational Data" }, { label: "EasyMorph", sub: "Rule transformation · cleansing · mapping" }, { label: "Azure Data Factory", sub: "Orchestration · triggers · integration" }, { label: "Databricks / PySpark", sub: "Scalable processing · transformation" }, { label: "SQL Server Staging" }, { label: "Validation & Troubleshooting" }, { label: "Downstream Healthcare / Billing Workflows" }] },
    howTitle: "Data becomes usable one verifiable stage at a time.",
    howBody: "Every record moves from ingestion through standardization and staging to validation, with a trace path when records are omitted or change unexpectedly.",
    steps: ["Ingest", "Standardize", "Transform", "Stage", "Validate", "Trace", "Deliver"],
    outcomesLabel: "Documented operational outcomes",
    outcomes: ["Standardized healthcare data fields", "Repeatable transformation logic", "Structured multi-stage processing", "Consistent missing-value handling", "More traceable investigation of omitted records", "Reliable staging for downstream workflows", "Improved maintainability of repeatable transformations"],
    tags: ["EasyMorph", "Databricks", "PySpark", "Azure Data Factory", "SQL Server", "Python", "SQL"],
    solutionOutcome: { intro: "Healthcare data now moves through standardized, orchestrated pipelines where each transformation is validated, traceable and staged cleanly for downstream use.", outcomes: ["Standardized data transformation logic", "Structured, orchestrated processing runs", "Clearer traceability from source to output", "Stronger validation and data-quality checks", "Cleaner staging for downstream systems", "Maintainable, documented data workflows"] },
    explore: [{ type: "Insight", title: "Healthcare data pipeline modernization", body: "Make ingestion, validation and record traceability visible before replacing any platform.", to: "/insights/healthcare-data-pipeline-modernization" }, { type: "Insight", title: "Data engineering for growing businesses", body: "How a reliable path from source systems to business information is built and kept working.", to: "/insights/data-engineering-growing-businesses" }, sol.data],
    ctaTitle: "Where is healthcare data becoming difficult to trust or process?",
    ctaBody: "Describe the source data, the rules it has to satisfy and where downstream teams stop trusting it.",
    cta: "Discuss Your Healthcare Data Pipeline",
  },
  {
    slug: "spreadsheet-project-tracking-digitalization", crumb: "Spreadsheet Project Tracking", category: "Digital transformation · Project operations", eyebrow: "Case study · Process digitalization", visual: "digitalization",
    title: "Replacing spreadsheet-driven project tracking with a structured processing and billing workflow.",
    heroDescription: "A project-operations workflow moving from spreadsheet-dependent processing toward structured ingestion, reconciliation, API-based processing and digital billing support.",
    cardProblem: "Project information was being handled through spreadsheet-based processes that required structured ingestion, reconciliation and downstream handling.",
    cardTransformation: "A data-processing service automatically handled Excel and JSON project information, reconciled data and exposed REST APIs for processing, export, tracking and billing workflows.",
    metaTitle: "Spreadsheet Project Tracking Digitalization", metaDescription: "How spreadsheet-driven project tracking moved to automated Excel and JSON ingestion, reconciliation, REST APIs, structured export and billing support.",
    contextTitle: "A spreadsheet routine turned into a dependable service.",
    context: [["Business environment", "Construction and project operations"], ["Starting point", "Spreadsheet-driven project-data processing"], ["Solution focus", "Automated ingestion, reconciliation and API services"], ["Connected workflow", "Project tracking and client billing"]],
    challengeTitle: "The spreadsheet was carrying more operational responsibility than it should.",
    challengeBody: "Project information arriving through Excel and JSON required processing and reconciliation before it could reliably support project tracking and billing activities.",
    challenges: [{ title: "Spreadsheet-dependent processing" }, { title: "Mixed Excel and JSON inputs" }, { title: "Reconciliation requirements" }, { title: "Project and billing data needing a structured flow" }],
    solutionTitle: "Turn project data into a service, not a spreadsheet routine.",
    solutionBody: "A backend processing service took over ingestion and reconciliation, then exposed the results through APIs that project tracking, billing and export could all rely on.",
    capabilities: ["Excel ingestion", "JSON ingestion", "Automated processing", "Data reconciliation", "REST APIs", "Structured export", "Project tracking support", "Billing workflow support"],
    architecture: { title: "One processing path feeding tracking and billing.", caption: "Project data service: Excel and JSON inputs flow through ingestion, processing and reconciliation into a REST API layer that serves project tracking and billing workflows and structured export.", flow: [{ label: "Excel / JSON Project Data" }, { label: "Ingestion Service" }, { label: "Processing & Reconciliation" }, { label: "REST API Layer" }, { group: ["Project Tracking", "Billing Workflow"] }, { label: "Structured Export / Downstream Use" }] },
    howTitle: "Project data moves from file to billing without manual reshaping.",
    howBody: "Incoming files are parsed and reconciled once, then made available to every downstream use through the same API.",
    steps: ["Receive", "Parse", "Reconcile", "Process", "Expose", "Track / Bill", "Export"],
    outcomesLabel: "Documented operational outcomes",
    outcomes: ["Structured processing of project data", "Automated ingestion path", "Defined reconciliation workflow", "API-accessible processing", "Digital project-tracking support", "Connected billing-data workflow"],
    tags: ["REST APIs", "Excel Processing", "JSON", "Data Reconciliation", "Backend Services", "API Integration"],
    solutionOutcome: { intro: "Project tracking and billing inputs now flow through structured ingestion and defined reconciliation instead of manual spreadsheet handling.", outcomes: ["Reduced dependence on spreadsheet handling", "Structured ingestion of project data", "Defined, repeatable reconciliation steps", "API-enabled processing between systems", "More consistent project and billing workflows", "Controlled export for downstream reporting"] },
    explore: [{ type: "Insight", title: "Digital transformation starts with fragmentation", body: "Understand where the operation disconnects before buying another system.", to: "/insights/digital-transformation-fragmented-systems" }, sol.dt, sol.integration],
    ctaTitle: "Which spreadsheet has quietly become part of your operating system?",
    ctaBody: "Tell us which file the operation depends on, who touches it and what happens downstream.",
    cta: "Map a Spreadsheet-Heavy Workflow",
  },
  {
    slug: "cloud-native-dotnet-modernization", crumb: "Cloud-Native .NET Modernization", category: "Application modernization · Cloud engineering", eyebrow: "Case study · Application modernization", visual: "modernization",
    title: "Modernizing a .NET application for cloud-hosted, event-driven delivery.",
    heroDescription: "Enterprise application engineering spanning API modernization, data access, framework upgrades, asynchronous processing, AWS services, observability and controlled deployment practices.",
    cardProblem: "Enterprise services needed to evolve across frameworks, dependencies, APIs, data access, asynchronous processing and cloud deployment without disrupting ongoing delivery.",
    cardTransformation: "Modern .NET APIs, structured persistence, cloud-hosted services, event-driven processing and stronger deployment practices created a more maintainable engineering environment.",
    metaTitle: "Cloud-Native .NET Modernization", metaDescription: "Modernizing .NET services with ASP.NET Core APIs, Entity Framework Core, event-driven AWS processing, Terraform and controlled CI/CD deployment.",
    contextTitle: "Modernization inside an application that had to keep delivering.",
    context: [["Application environment", "Enterprise service-oriented applications"], ["Engineering scope", "Backend APIs, persistence and modernization"], ["Cloud scope", "AWS-hosted and event-driven workloads"], ["Delivery scope", "CI/CD, infrastructure and deployment validation"]],
    challengeTitle: "Modernization has to improve the system without interrupting the business around it.",
    challengeBody: "Framework versions, dependencies, API contracts, data access and deployment all needed to move forward while the services continued supporting active work.",
    challenges: [{ title: "Framework and dependency evolution" }, { title: "API and data-access changes" }, { title: "Asynchronous processing" }, { title: "Cloud operations and deployment reliability" }],
    solutionTitle: "Modernize the application layer and the delivery environment together.",
    solutionBody: "Application code, persistence, messaging and deployment practices were upgraded as one engineering environment, so changes could be validated and released in a controlled way.",
    capabilities: ["C#/.NET backend services", "ASP.NET Core APIs", "Entity Framework Core", "REST API development", "Authentication and authorization", "Framework upgrades", "Dependency modernization", "Database migration support", "Asynchronous messaging", "AWS-hosted services", "Application logging", "Deployment validation", "API documentation"],
    architecture: { title: "A modernization architecture pattern.", caption: "Representative modernization architecture pattern, not a literal client network diagram: ASP.NET Core APIs and a service layer persist through Entity Framework Core with a parallel SQS/SNS messaging path, hosted on ECS/Fargate with supporting AWS services and a CI/CD and Terraform foundation.", flow: [{ label: "Application Consumers" }, { label: "ASP.NET Core REST APIs" }, { label: "Business / Service Layer" }, { group: ["Entity Framework Core → Relational Data", "Message Processing → SQS / SNS"] }, { label: "ECS / Fargate", sub: "Cloud environment" }], aside: { title: "Supporting services & delivery foundation", items: ["Secrets Manager", "DynamoDB", "CloudWatch", "CI/CD", "Terraform"] } },
    howTitle: "Change moves through assessment, validation and observation.",
    howBody: "Each modernization step is assessed, applied, validated and observed in the running environment before the next one begins.",
    steps: ["Assess", "Upgrade", "Refactor", "Integrate", "Validate", "Deploy", "Observe"],
    outcomesLabel: "Documented engineering outcomes",
    outcomes: ["Modernized framework and dependency foundations", "Structured REST service development", "Database and ORM-based persistence", "Event-driven processing capability", "Cloud-hosted application operations", "Improved API documentation", "Controlled deployment and validation practices"],
    tags: ["C#", ".NET", "ASP.NET Core", "Entity Framework Core", "AWS", "SQS / SNS", "ECS / Fargate", "Terraform"],
    solutionOutcome: { intro: "The application now rests on a modern, maintainable .NET foundation with clearer service boundaries, observable behaviour and controlled release paths.", outcomes: ["A maintainable, modernized application foundation", "Clearer service and module boundaries", "Upgraded frameworks and dependencies", "Asynchronous processing for background work", "Better observability through logs and monitoring", "Controlled, repeatable deployments", "An architecture that is easier to evolve"] },
    explore: [sol.modern, sol.cloud, sol.tech],
    ctaTitle: "What is making your current application harder to change?",
    ctaBody: "Bring the framework, dependency, deployment or architecture constraint slowing your team down.",
    cta: "Review a Modernization Constraint",
  },
  {
    slug: "snowflake-dbt-analytics-platform", crumb: "Snowflake + dbt Analytics Platform", category: "Data engineering · Analytics platform", eyebrow: "Case study · Data engineering", visual: "ai",
    title: "Building a maintainable analytics pipeline from source ingestion to validated models.",
    heroDescription: "A modern data-engineering workflow connecting source ingestion, cloud warehousing, transformation, analytical modelling, validation and controlled deployment.",
    cardProblem: "Source data needed a repeatable path through ingestion, transformation, modelling and validation before it could reliably support analytics.",
    cardTransformation: "Fivetran ingestion, Snowflake storage and processing, dbt transformation models and controlled Azure DevOps workflows created a structured analytical data pipeline.",
    metaTitle: "Snowflake and dbt Analytics Platform", metaDescription: "A maintainable analytics pipeline using Fivetran ingestion, Snowflake warehousing, dbt models, SQL validation and Azure DevOps deployment workflows.",
    contextTitle: "A clear separation between ingestion, transformation and use.",
    context: [["Solution focus", "Analytical data platform"], ["Ingestion", "Fivetran"], ["Data warehouse", "Snowflake"], ["Transformation & delivery", "dbt, SQL and Azure DevOps"]],
    challengeTitle: "Analytics is only as dependable as the pipeline underneath it.",
    challengeBody: "Reports and analysis needed a predictable path from source systems to modelled data, with transformation logic that could be reviewed, validated and changed safely.",
    challenges: [{ title: "Source-system ingestion" }, { title: "Repeatable transformation" }, { title: "Data-model validation" }, { title: "Controlled data-platform delivery" }],
    solutionTitle: "A clear path from source data to analytics-ready models.",
    solutionBody: "Managed ingestion landed data in Snowflake, dbt models turned it into analytical structures, and pull-request workflows kept every change reviewable before deployment.",
    capabilities: ["Source ingestion", "Fivetran integration", "Snowflake storage", "dbt transformation", "Analytical modelling", "SQL validation", "Pipeline maintenance", "Azure DevOps pull requests", "Controlled deployment workflows"],
    architecture: { title: "Source to model, with delivery controls underneath.", caption: "Analytics pipeline: source systems flow through Fivetran into Snowflake raw and staging layers, dbt transformation models and validated analytical models for reporting, supported by Azure DevOps, Git and CI/CD.", flow: [{ label: "Source Systems" }, { label: "Fivetran" }, { label: "Snowflake Raw / Staging" }, { label: "dbt Transformation Models" }, { label: "Validated Analytical Models" }, { label: "Reporting / Analytics Consumption" }], aside: { title: "Supporting layer", items: ["Azure DevOps", "Git", "CI/CD"] } },
    howTitle: "Every model change follows the same controlled path.",
    howBody: "Data is ingested and stored once, transformed and modelled in code, validated, then deployed through reviewed changes before anyone consumes it.",
    steps: ["Ingest", "Store", "Transform", "Model", "Validate", "Deploy", "Consume"],
    outcomesLabel: "Documented engineering outcomes",
    outcomes: ["Maintainable transformation workflows", "Structured ingestion and modelling", "Validated analytical datasets", "Controlled code-change process", "Repeatable environment delivery", "Clearer separation between ingestion, transformation and analytical use"],
    tags: ["Snowflake", "dbt", "Fivetran", "SQL", "Python", "Azure DevOps", "CI/CD"],
    solutionOutcome: { intro: "Analytics data now moves through clearly layered ingestion, transformation and delivery, with validated models feeding a dependable reporting foundation.", outcomes: ["Structured ingestion into Snowflake", "Maintainable, modular dbt transformations", "Tested and validated data models", "Clear raw, transformed and analytics layers", "Controlled deployment of data changes", "A stronger foundation for reporting"] },
    explore: [{ type: "Insight", title: "Modern data stack: Snowflake, dbt, Fivetran and Databricks", body: "What each platform layer does and when you actually need it.", to: "/insights/modern-data-stack" }, sol.data, sol.cloud],
    ctaTitle: "Where does your data stop becoming dependable?",
    ctaBody: "Show us where source data, transformation or reporting starts producing numbers people question.",
    cta: "Map Your Data Pipeline",
  },
  {
    slug: "snowflake-data-warehouse-modernization", crumb: "Snowflake Warehouse Modernization", category: "Data modernization · Delivery automation", eyebrow: "Case study · Data platform modernization", visual: "modernization",
    title: "Moving a Snowflake data platform toward versioned, repeatable delivery.",
    heroDescription: "A data-platform modernization effort spanning migration scripts, database objects, dbt transformation, versioned deployment, backfill validation and incremental-load troubleshooting.",
    cardProblem: "Database views, migration scripts, stored procedures, incremental loads and environment changes required a more controlled way to evolve the data platform.",
    cardTransformation: "Snowflake migration work, dbt models, SchemaChange practices and CI/CD workflows brought more structure to database change, deployment and validation.",
    metaTitle: "Snowflake Data Warehouse Modernization", metaDescription: "Bringing versioned, repeatable delivery to a Snowflake warehouse with dbt models, SchemaChange, Azure DevOps CI/CD, backfill and incremental-load validation.",
    contextTitle: "Database change treated as an engineering discipline.",
    context: [["Platform", "Snowflake data warehouse"], ["Modernization scope", "Views, stored procedures, migration and dbt models"], ["Delivery scope", "Versioning and automated deployment"], ["Operational scope", "Incremental loads, backfills and ETL validation"]],
    challengeTitle: "Data platforms become difficult to change when database logic and deployment drift apart.",
    challengeBody: "Existing views, procedures and tasks carried business logic that had to be migrated, retired or versioned, while incremental loads and environments kept running.",
    challenges: [{ title: "Existing database objects" }, { title: "Migration and retirement of obsolete logic" }, { title: "Incremental-load reliability" }, { title: "Environment-specific deployment and validation" }],
    solutionTitle: "Treat data-platform change like software delivery.",
    solutionBody: "Database objects moved into source control, dbt and SchemaChange versioned the changes, and CI/CD pipelines deployed them per environment with validation afterwards.",
    capabilities: ["Snowflake migration scripts", "Database views", "Stored-procedure management", "View-to-dbt conversion", "SchemaChange versioning", "Azure DevOps deployment", "Environment-based delivery", "Backfill validation", "Incremental-load investigation", "ETL troubleshooting", "Rollback concepts", "Deployment logging"],
    architecture: { title: "From unversioned objects to controlled environments.", caption: "Warehouse modernization: existing Snowflake views, procedures and tasks are migrated into dbt models and SchemaChange scripts, held in source control and deployed through Azure DevOps CI/CD to Snowflake environments, followed by validation, backfill and incremental-load checks.", flow: [{ label: "Existing Snowflake Objects", sub: "Views · Procedures · Tasks" }, { label: "Migration / Refactoring" }, { label: "dbt Models + SchemaChange" }, { label: "Source Control" }, { label: "Azure DevOps CI/CD" }, { label: "Snowflake Environments" }, { label: "Validation · Backfill · Incremental Load Checks" }] },
    howTitle: "Every database change becomes versioned and verifiable.",
    howBody: "Objects are assessed, migrated or modelled, versioned, deployed through pipelines and validated against loads and backfills.",
    steps: ["Assess", "Migrate", "Model", "Version", "Deploy", "Validate", "Monitor"],
    outcomesLabel: "Documented engineering outcomes",
    outcomes: ["More structured data transformation", "Version-controlled database change", "Controlled environment deployment", "Backfill verification", "Incremental-load troubleshooting", "Clearer deployment validation", "Retirement of obsolete database objects where appropriate"],
    tags: ["Snowflake", "dbt", "SchemaChange", "Azure DevOps", "SQL", "Terraform", "Python", "CI/CD"],
    solutionOutcome: { intro: "Warehouse changes are now versioned, deployed and validated through a governed process, so the platform can evolve without losing control of its logic.", outcomes: ["Version-controlled data and schema changes", "Maintainable transformation logic", "Controlled deployment across environments", "Validated backfills before release", "Better handling of incremental loads", "Governed evolution of the data platform"] },
    explore: [{ type: "Insight", title: "Data warehouse modernization", body: "Move from stored procedures and views to dbt, CI/CD and governed models safely.", to: "/insights/data-warehouse-modernization" }, { ...sol.data, body: "Turn warehouse logic into versioned, testable data models." }, { ...sol.cloud, body: "Bring CI/CD and environment discipline to data-platform delivery." }, ],
    ctaTitle: "Is your data platform harder to change than the data itself?",
    ctaBody: "Tell us which views, procedures or deployment steps make every warehouse change feel risky.",
    cta: "Modernize Your Data Delivery Workflow",
  },
  {
    slug: "cloud-data-migration-recovery", crumb: "Cloud Data Migration & Recovery", category: "Cloud engineering · Data migration", eyebrow: "Case study · Cloud data migration", visual: "capacity",
    title: "Designing migration and recovery workflows where failure cannot be silent.",
    heroDescription: "Cloud data-movement workflows built around transfer orchestration, status visibility, archival, recovery and failure handling where consistency mattered as much as successful transfer.",
    cardProblem: "Moving and archiving data required reliable transfer, visible status and explicit failure handling because incomplete or duplicated movement could create serious data-consistency problems.",
    cardTransformation: "Backend workflows connected cloud storage transfer, migration status, archival and recovery handling into a more observable data-movement process.",
    metaTitle: "Cloud Data Migration, Archival & Recovery", metaDescription: "Designing observable cloud data migration with orchestrated transfer, status tracking, failure detection, archival and recovery workflows on Google Cloud.",
    contextTitle: "Data movement engineered for consistency, not just completion.",
    context: [["Solution focus", "Data migration, archival and recovery"], ["Cloud scope", "Cloud storage movement and orchestration"], ["Reliability focus", "Status tracking and failure handling"], ["Engineering concern", "Prevent silent loss, duplication or incomplete transfer states"]],
    challengeTitle: "Moving data is easy to start. Knowing it moved correctly is the difficult part.",
    challengeBody: "Long-running transfers can partially succeed, fail midway or run twice. The workflow needed every state to be recorded so problems surfaced instead of hiding.",
    challenges: [{ title: "Long-running data movement" }, { title: "Migration-state visibility" }, { title: "Failure and exception handling" }, { title: "Archive and recovery requirements" }],
    solutionTitle: "Make every transfer state visible and recoverable.",
    solutionBody: "An orchestrator drove cloud storage transfers while a parallel control path tracked status, detected failures and routed them into retry, recovery or archive handling.",
    capabilities: ["Migration orchestration", "Cloud-storage transfer", "Asynchronous processing", "Status tracking", "Archival workflows", "Recovery workflows", "Failure handling", "Consistency checks", "Operational observability"],
    architecture: { title: "A transfer path with a control plane beside it.", caption: "Cloud data migration: a migration orchestrator moves data from source storage through cloud storage transfer to destination storage, while a parallel control plane tracks status, detects failures, handles retry and recovery, and records archive state.", flow: [{ label: "Source Application / Storage" }, { label: "Migration Orchestrator" }, { label: "Cloud Storage Transfer" }, { label: "Destination Storage" }], aside: { title: "Parallel control plane", items: ["Status Tracking", "Failure Detection", "Retry / Recovery Handling", "Archive State"] } },
    howTitle: "A migration is only finished when its state is known.",
    howBody: "Transfers are prepared, tracked and validated, then archived or routed to recovery before the migration is formally closed.",
    steps: ["Prepare", "Transfer", "Track", "Validate", "Archive", "Recover if required", "Close"],
    outcomesLabel: "Documented engineering outcomes",
    outcomes: ["Explicit migration-state tracking", "Structured archive handling", "Defined recovery workflows", "Failure-aware data movement", "Better operational visibility into long-running transfers", "Consistency-focused migration handling"],
    tags: ["Google Cloud", "Cloud Storage", "Storage Transfer Service", "Cloud Tasks", "REST APIs", "Docker", "CI/CD"],
    solutionOutcome: { intro: "Data migration now runs with visible states, structured archival and defined recovery paths, making every transfer traceable and failure-aware.", outcomes: ["Visible migration and transfer states", "Structured archival of moved data", "Defined recovery paths for interrupted runs", "Failure-aware transfer handling", "Stronger traceability across the migration", "Clear operational status for support teams"] },
    explore: [{ ...sol.cloud, body: "Design cloud workloads that are observable and recoverable." }, sol.integration, sol.modern],
    ctaTitle: "What happens when your migration does not complete cleanly?",
    ctaBody: "Describe the data you need to move, archive or recover and what a partial failure would cost you.",
    cta: "Plan a Safer Data Migration",
  },
  {
    slug: "enterprise-reporting-data-accuracy", crumb: "Enterprise Reporting & Data Accuracy", category: "Data engineering · Enterprise reporting", eyebrow: "Case study · Enterprise reporting", visual: "trackTrace",
    title: "Strengthening enterprise reporting by tracing business logic back to the data.",
    heroDescription: "Enterprise reporting work connecting SQL Server data structures, stored procedures, report definitions, parameters, business rules and validation around reporting accuracy.",
    cardProblem: "Report filters, statuses and business rules depended on data moving correctly through tables, views, stored procedures and reporting definitions.",
    cardTransformation: "A structured troubleshooting and enhancement approach traced reporting requirements from database logic through SSRS/RDL reports and into validation and UAT.",
    metaTitle: "Enterprise Reporting & Data Accuracy", metaDescription: "Tracing enterprise report logic from SQL Server tables, views and stored procedures through SSRS/RDL parameters and business rules into validation and UAT.",
    contextTitle: "Reporting treated as the last layer of a data flow.",
    context: [["Reporting environment", "Enterprise business reporting"], ["Data platform", "SQL Server"], ["Reporting layer", "SSRS / RDL"], ["Engineering scope", "Enhancement, defect analysis, validation and UAT"]],
    challengeTitle: "A reporting problem can begin several layers before the report itself.",
    challengeBody: "When a report shows the wrong rows or totals, the cause may sit in a join, a view, a stored procedure, a parameter or a status rule. Each layer had to be checkable.",
    challenges: [{ title: "Complex SQL logic" }, { title: "Parameter and date filters" }, { title: "Status-based business rules" }, { title: "Data-versus-code defect investigation" }],
    solutionTitle: "Trace the report from presentation back to source logic.",
    solutionBody: "Enhancements and defects were worked through layer by layer, from report output back to source tables, so fixes landed where the logic actually lived and were validated with the business.",
    capabilities: ["SQL investigation", "Joins and business rules", "Stored procedures", "Views", "Report definitions", "SSRS/RDL enhancement", "Parameter handling", "Date filters", "Status logic", "Report-column enhancement", "Local testing", "Defect analysis", "UAT validation"],
    architecture: { title: "A reporting stack with a root-cause loop.", caption: "Enterprise reporting flow: source tables feed views and stored procedures, then parameters and business rules, SSRS/RDL definitions and report output, with validation and UAT feeding back to source tables and stored procedures for root-cause investigation.", flow: [{ label: "Source Tables" }, { label: "Views" }, { label: "Stored Procedures" }, { label: "Parameters & Business Rules" }, { label: "SSRS / RDL" }, { label: "Report Output" }, { label: "Validation / UAT" }], feedback: "Troubleshooting loop: Validation / UAT → Source Tables / Stored Procedures" },
    howTitle: "Every report issue is followed to its real source.",
    howBody: "Problems are reproduced, traced through each layer, corrected where the logic lives, then tested and accepted against the business requirement.",
    steps: ["Reproduce", "Trace", "Validate Data", "Inspect Logic", "Correct", "Test", "UAT"],
    outcomesLabel: "Documented engineering outcomes",
    outcomes: ["More traceable report logic", "Validated filter behaviour", "Structured status-rule investigation", "Clearer distinction between configuration and code defects", "Report changes validated against business requirements", "Stronger end-to-end understanding of reporting data flow"],
    tags: ["SQL Server", "SQL", "Stored Procedures", "SSRS", "RDL", "Data Validation", "UAT"],
    solutionOutcome: { intro: "Enterprise reports now run on traceable logic with validated filters and structured acceptance testing, giving the business a more dependable reporting base.", outcomes: ["Traceable report logic from source to output", "Validated filters and parameters", "Clearer handling of business rules", "Structured user acceptance testing", "Faster defect isolation through documented analysis", "A stronger foundation for reporting reliability"] },
    explore: [{ type: "Insight", title: "Operational reporting modernization", body: "Trace management information from source ownership through validation and reconciliation.", to: "/insights/operational-reporting-modernization" }, { type: "Insight", title: "Data silos: why you have data but lack visibility", body: "The five forms of data fragmentation and how to close the visibility gap.", to: "/insights/data-silos-business-visibility" }, { ...sol.data, body: "Make reporting data traceable from source to output." }, sol.dt],
    ctaTitle: "Can you trace a reporting problem all the way back to its source?",
    ctaBody: "Bring the report people doubt and the logic behind it. We will help work out where it is breaking.",
    cta: "Review a Reporting Reliability Problem",
  },
];

export const getCaseStudy = (slug: string) => caseStudies.find((c) => c.slug === slug);
