import type { ExploreItem } from "../components/continue-exploring";

const trackTrace: ExploreItem = { type: "Case study", title: "A connected field-service platform", body: "See how technician work, stock, communication, and operational status were brought into one system.", to: "/case-studies/track-trace" };
const engineering: ExploreItem = { type: "Case study", title: "Extending engineering delivery", body: "Explore a flexible model for adding capability around real delivery demand.", to: "/case-studies/engineering-capacity" };
const digitalization: ExploreItem = { type: "Insight", title: "Replacing Excel-based business processes", body: "A staged way to move from shared workbooks to connected operations.", to: "/insights/digitalize-excel-workflows" };
const capacity: ExploreItem = { type: "Insight", title: "Choosing the right capacity model", body: "Compare a specialist, pod, and project team by ownership and uncertainty.", to: "/insights/staff-augmentation-vs-dedicated-team-vs-outsourcing" };
const ai: ExploreItem = { type: "Insight", title: "Find an AI use case worth testing", body: "Start with recurring work, available information, and a useful outcome.", to: "/insights/ai-workflow-automation" };
const modernization: ExploreItem = { type: "Insight", title: "Modernize or replace?", body: "Use business criticality, constraints, and migration risk to choose a path.", to: "/insights/application-modernization-refactor-replatform-rebuild-replace" };

const solutionItems: Record<string, ExploreItem[]> = {
  "software-engineering": [trackTrace, { type: "Insight", title: "Modernize or replace?", body: "Separate product value from the architecture constraints around it.", to: "/insights/application-modernization-refactor-replatform-rebuild-replace" }, { type: "Industry", title: "Fintech product engineering", body: "See how roadmap pressure changes the capacity decision.", to: "/industries/fintech" }],
  "digital-transformation": [trackTrace, digitalization, { type: "Assessment", title: "Digitalization readiness", body: "Identify where operations are losing time before deciding what to build.", to: "/digitalization-assessment" }],
  integration: [trackTrace, digitalization, { type: "Industry", title: "Logistics & Supply Chain", body: "See where connected information changes operational control.", to: "/industries/logistics" }],
  "erp-business-systems": [trackTrace, digitalization, { type: "Solution", title: "API & System Integration", body: "Connect useful systems rather than replacing them by default.", to: "/solutions/integration" }],
  "engineering-capacity": [engineering, capacity, { type: "Assessment", title: "Engineering capacity assessment", body: "Clarify the capability, ownership, and delivery model you need.", to: "/engineering-capacity-assessment" }],
  "ai-automation": [ai, { type: "Assessment", title: "AI opportunity assessment", body: "Find where AI could actually help one recurring workflow.", to: "/ai-opportunity-assessment" }, { type: "Solution", title: "Data Engineering & Analytics", body: "Build dependable information foundations for useful decisions.", to: "/solutions/data-engineering" }],
  "application-modernization": [modernization, { type: "Solution", title: "Cloud & Platform Engineering", body: "Strengthen the foundation beneath software that needs to change.", to: "/solutions/cloud-platform-engineering" }, engineering],
  "cloud-platform-engineering": [trackTrace, modernization, { type: "Solution", title: "Application Modernization", body: "Sequence architecture and platform change around continuity.", to: "/solutions/application-modernization" }],
  "data-engineering": [trackTrace, digitalization, { type: "Solution", title: "API & System Integration", body: "Establish how trustworthy records move between systems.", to: "/solutions/integration" }],
};

const industryItems: Record<string, ExploreItem[]> = {
  logistics: [trackTrace, digitalization, { type: "Solution", title: "Digital Transformation", body: "Replace fragmented operations with connected digital workflows.", to: "/solutions/digital-transformation" }],
  "technology-it-services": [engineering, capacity, { type: "Solution", title: "Engineering Capacity", body: "Add capability around current delivery demand.", to: "/solutions/engineering-capacity" }],
  fintech: [{ type: "Insight", title: "Fintech engineering ownership", body: "Decide what to own, extend or delegate while retaining product accountability.", to: "/insights/fintech-what-to-outsource" }, { type: "Insight", title: "Reliable asynchronous workflows", body: "Design retries, reconciliation and audit around critical processing.", to: "/insights/fintech-asynchronous-workflows" }, { type: "Insight", title: "Fintech data engineering", body: "Build a traceable path from transaction to management information.", to: "/insights/fintech-data-engineering" },{ type: "Case study", title: "Digital brokerage platform", body: "Onboarding, payments, trading and reporting connected through one platform.", to: "/case-studies/digital-brokerage-platform" }, { type: "Insight", title: "Scaling fintech engineering after funding", body: "Decide which capacity to hire, extend or deliver as a bounded project.", to: "/insights/fintech-scale-engineering-after-funding" }, { type: "Insight", title: "Fintech platform modernization", body: "Modernize the constraint slowing the roadmap, not the whole platform.", to: "/insights/fintech-platform-modernization" }, { type: "Insight", title: "Fintech API & integration strategy", body: "Connect identity, payments, data, trading and reporting reliably.", to: "/insights/fintech-api-integration-strategy" }, capacity, { type: "Solution", title: "Software Engineering", body: "Build dependable products around a changing roadmap.", to: "/solutions/software-engineering" }],
  manufacturing: [{ type: "Insight", title: "Manufacturing digitalization in Africa", body: "Connect production, inventory and reporting around the handoffs that matter.", to: "/insights/manufacturing-digitalization-africa" }, { type: "Solution", title: "ERP / Business Systems", body: "Define the role of ERP, extensions, and operational applications.", to: "/solutions/erp-business-systems" }, { type: "Solution", title: "Data Engineering & Analytics", body: "Build reporting from accountable production records.", to: "/solutions/data-engineering" }],
  healthcare: [{ type: "Solution", title: "API & System Integration", body: "Connect supporting applications with explicit information responsibility.", to: "/solutions/integration" }, modernization, { type: "Assessment", title: "Digitalization readiness", body: "Examine one administrative workflow before defining a programme.", to: "/digitalization-assessment" }],
};

export function relatedForSolution(slug: string) { return solutionItems[slug] ?? []; }
export function relatedForIndustry(slug: string) { return industryItems[slug] ?? []; }

export const articleRelations: Record<string, ExploreItem[]> = {
  "application-modernization-refactor-replatform-rebuild-replace": [{ type: "Insight", title: "12 signs your legacy application is becoming a business risk", body: "Diagnose whether the application is constraining the business before choosing an intervention.", to: "/insights/legacy-application-business-risk" }, { type: "Insight", title: "Cloud migration vs cloud modernization", body: "Separate hosting from application and data change.", to: "/insights/cloud-migration-vs-cloud-modernization" }],
  "cloud-migration-vs-cloud-modernization": [{ type: "Insight", title: "Application modernization decision matrix", body: "Compare refactor, replatform, rebuild and replace when the application itself must change.", to: "/insights/application-modernization-refactor-replatform-rebuild-replace" }, { type: "Case study", title: "Cloud data migration & recovery", body: "Examine a documented pattern for transfer and recovery control.", to: "/case-studies/cloud-data-migration-recovery" }],
  "legacy-application-business-risk": [{ type: "Insight", title: "Application modernization decision matrix", body: "Turn an identified constraint into a practical choice of intervention.", to: "/insights/application-modernization-refactor-replatform-rebuild-replace" }, { type: "Insight", title: "Cloud migration vs cloud modernization", body: "Decide whether the problem is location, application design or data continuity.", to: "/insights/cloud-migration-vs-cloud-modernization" }],
  "digital-transformation-fragmented-systems": [{ type: "Insight", title: "Workflow automation strategy", body: "Decide which recurring process should be automated, integrated or redesigned first.", to: "/insights/workflow-automation-strategy" }, digitalization, trackTrace],
  "ai-workflow-automation": [{ type: "Insight", title: "Workflow automation strategy", body: "Prioritize the business process before deciding whether AI is required.", to: "/insights/workflow-automation-strategy" }, { type: "Solution", title: "AI & Intelligent Automation", body: "Shape a bounded proof around a real operating need.", to: "/solutions/ai-automation" }, { type: "Solution", title: "Data Engineering & Analytics", body: "Create the dependable information foundation useful automation requires.", to: "/solutions/data-engineering" }],
  "business-case-process-digitalization": [digitalization, trackTrace, { type: "Insight", title: "Workflow automation strategy", body: "Prioritize a measurable operational process before selecting automation.", to: "/insights/workflow-automation-strategy" }],
  "reduce-engineering-backlog": [engineering, capacity],
  "white-label-software-development": [engineering, capacity],
  "fintech-data-engineering": [{ type: "Case study", title: "Digital stock brokering platform", body: "See connected onboarding, payment, trading and reporting capabilities.", to: "/case-studies/digital-brokerage-platform" }, { type: "Insight", title: "Operational reporting modernization", body: "Trace reporting back to its source record and definitions.", to: "/insights/operational-reporting-modernization" }],
  "operational-reporting-modernization": [{ type: "Case study", title: "Enterprise reporting and data accuracy", body: "See how reporting logic, filters and validation became more traceable.", to: "/case-studies/enterprise-reporting-data-accuracy" }, { type: "Insight", title: "Data warehouse modernization", body: "Evolve transformations, testing and governance without a risky rewrite.", to: "/insights/data-warehouse-modernization" }],
  "ai-integration-readiness": [ai, { type: "Solution", title: "API & System Integration", body: "Create controlled interfaces between workflows, information and tools.", to: "/solutions/integration" }],
  "staff-augmentation-vs-dedicated-team-vs-outsourcing": [engineering, { type: "Solution", title: "Engineering Capacity", body: "Add delivery capability through the model the work actually needs.", to: "/solutions/engineering-capacity" }, { type: "Industry", title: "Technology & IT Services", body: "Review capacity decisions in the context of client delivery and changing demand.", to: "/industries/technology-it-services" }],
};