// Decision exercises and worked scenarios extend the existing sections without adding a new page layout.
export const practiceDepth: Record<string, Record<string, string[]>> = {
 "fintech-what-to-outsource": {governance:[
  "Before comparing proposals, run a responsibility exercise with a single consequential change. Suppose the business wants to add an alternative identity provider. Who decides whether its evidence is acceptable? Who maps the provider response to internal customer states? Who implements the adapter, tests a timeout, approves deployment, monitors failures and contacts the provider when a request is disputed? Fill every role with a named owner. If the same external team defines the policy, builds the integration, approves its own change and alone understands its support path, the outsourcing decision has quietly become an ownership decision.",
  "Translate the exercise into a delivery agreement. Describe the workstream, the internal decision owner, the acceptance evidence and the operational handover. Separate requirements that can be observed—such as a reviewed integration contract and a tested error path—from promises about speed or quality that cannot be checked. Agree how changing a requirement affects estimates and who authorizes the change. Repeat the exercise for another domain before applying the same model across the whole platform.",
  "A simple quarterly review can keep the boundary honest. Ask which external dependencies remain unexplained internally, which runbooks have been exercised and whether production access still matches current assignments. Review changes to customer promises or regulation with the appropriate owners, rather than assuming the original scope covers them. The result is a living allocation of authority and capacity: something leadership can modify as the team and product mature."
 ]},
 "fintech-asynchronous-workflows": {reconcile:[
  "Walk through a lost-response scenario with the product and operations teams. A customer submits a request; the server records it and sends work to a processor, but the browser times out before receiving the acknowledgement. The customer retries. The platform should recognize the original intent, show its current state and avoid a second business effect. Then suppose the provider accepted the action but its callback is delayed. The platform must not equate missing callback with confirmed failure. It can check provider status or place the request in investigation, depending on the provider contract.",
  "Now test the recovery route. An operator receives an exception showing the internal reference, external reference if available, last successful step and the exact disagreement. Can the operator tell whether a retry is safe? Can they link a manual correction to the original request rather than overwriting history? Can support explain the state to the customer without exposing internal error details or implying completion too early? These questions determine what to log and what tooling to build. They are far more informative than a demonstration in which every service responds on time.",
  "Finally decide what 'done' means for the journey. A processor may complete its step before a downstream report or notification is updated. Define which transition is customer-facing completion, which side effects can lag and how long an unresolved item is allowed to remain before escalation. Keep those time windows as product and provider-specific decisions rather than adopting an invented universal threshold. A reliable asynchronous architecture makes those distinctions visible and testable."
 ]},
 "fintech-data-engineering": {models:[
  "Use a worked reporting question to test the design. A leadership team wants to know how many customer onboarding requests reached an approved state during a month. The source system may contain the current status but not the history of when it changed. An external identity provider may confirm verification at a different time. A CRM may count the customer when an account manager creates a record. Before joining tables, agree whether the measure counts first approval, latest approval or currently approved customers, and whether later reversals change the historic result.",
  "Build a narrow lineage path for that definition. Capture the authoritative status event and its identifier, preserve its event and ingestion timestamps, test for missing or repeated events, then model the approved count with explicit exclusions. Compare a sample of modeled records with the source and investigate discrepancies rather than adjusting the chart to an expected total. Publish the definition and freshness alongside the report. A manager can then understand why the number differs from a CRM count without declaring either system broken.",
  "When a new question arrives—such as whether approvals differ by onboarding channel—inspect whether the relevant field has a trustworthy historical record. If it does not, state that limitation and add collection or validation before promising a trend. This exercise keeps platform scope tied to decisions. It also shows when a warehouse is worth its maintenance cost: repeated cross-source history and governed definitions justify a shared model in a way that a single current-status report may not."
 ]},
 "white-label-software-development": {handover:[
  "A useful acceptance rehearsal begins before the final invoice. Ask the agency's reviewer to clone the repository into its own environment, run checks, deploy a safe release and locate one known failure using the supplied runbook. Ask someone on the account team to explain how a customer request becomes a prioritized engineering task and who may approve a change in scope. If either group depends on a partner's private account or unwritten knowledge, the work is not yet truly transferable.",
  "Rehearse an end-customer question too: why does one report differ from another? The agency should be able to find the definition, source owner and relevant architectural decision without inventing an answer. The partner can contribute the technical explanation, but the agency must own what it communicates. This is especially important when a white-label arrangement makes the engineering team less visible to the customer. Brand continuity is valuable only when it does not obscure responsibility.",
  "Close with a transition inventory: code, environments, test data, licenses, service ownership, unresolved defects, support contacts and renewal dates. Confirm which credentials must be rotated and who retains access. A client may retain the partner for future work, but it should be a deliberate choice based on value rather than inability to leave."
 ]},
 "evaluate-software-engineering-partner": {pilot:[
  "A pilot scorecard could use four evidence columns: expected practice, observed artifact, unresolved question and owner of the next decision. Under technical reasoning, capture the candidate's trade-off on a real integration. Under delivery, capture the reviewed change and accepted test. Under security, capture the approved access path, not an unverified assertion. Under continuity, ask an internal engineer to operate the result. This makes the evaluation discussable across engineering, product, procurement and leadership without reducing everything to a generic numerical grade.",
  "Compare the effort on both sides. If a partner delivers a change quickly but repeatedly waits for the client to clarify business rules, the client might need stronger product ownership. If internal reviewers spend significant time correcting basic tests, the partner's quality system may be weak. Separate those causes before deciding to expand or reject the relationship. A pilot is also a test of the buyer's readiness to work with any partner, not merely a vendor audition.",
  "At the decision meeting, record what was actually shown, what remains unknown and whether a larger scope changes the risk profile. A successful isolated feature does not demonstrate incident response, long-term support or handling of sensitive production access. Scale the next engagement only with controls appropriate to its actual responsibilities."
 ]},
 "reduce-engineering-backlog": {model:[
  "Use a short diagnostic cycle before procuring capacity. Select a representative sample of aging items and mark where each waited, why it waited and whether it still matters. Then watch a few items travel from request to deployment. If most time is spent before clarification, improve intake and acceptance. If changes wait for a shared component, consider a boundary redesign or a specialist. If reviewed work waits for release, improve the deployment path. Revisit the sample after an intervention rather than assuming a lower backlog count means customers receive value sooner.",
  "An example illustrates why the label matters. A team with many tickets may have developers available but depend on one person to approve all data-model changes. Adding a frontend pod creates more pull requests that wait for the same reviewer. Instead, the organization could document model conventions, delegate bounded reviews and create tests for key invariants. Once that constraint eases, extra implementation capacity might become valuable. The order of intervention determines whether the new capacity produces completed work or a larger queue.",
  "Retire stale work explicitly. A backlog with every idea ever suggested cannot be 'cleared' through engineering effort alone. Give stakeholders a predictable way to resubmit deferred ideas when context changes, and distinguish commitments from options. A healthy backlog is not necessarily empty; it is governed, understandable and aligned to current decisions."
 ]},
 "ai-integration-readiness": {pilot:[
  "For a controlled example, imagine an assistant that drafts a response to a customer's operational question. It should retrieve only documents the assigned agent can view, cite the relevant current policy and mark uncertainty when the question falls outside it. A human reviewer approves the draft. The pilot can record where the model chose the wrong source, where the source itself was ambiguous and where the reviewer needed to rewrite the answer. Those are different problems and lead to different interventions: retrieval rules, knowledge ownership or workflow redesign.",
  "Do not expand the same assistant into action-taking merely because drafting performs well. Updating a customer record needs scoped identity, validated fields, an approval policy and a way to detect if a tool call succeeded after a timeout. A refund or notification may have consequences that cannot be casually undone. Introduce actions one at a time, with a dry-run representation where practical and an explicit human checkpoint when risk warrants it. Monitor rejected requests and unexpected tool usage as well as completed work.",
  "Agree who owns the model configuration, knowledge index, API permissions, review policy and incident response. Those owners may sit in different functions. If a pilot cannot identify them, its most useful finding may be an organizational readiness gap rather than a model shortcoming."
 ]},
 "business-case-process-digitalization": {pilot:[
  "Consider a purchase-approval process in which a requester emails a spreadsheet, an approver replies in another thread and a coordinator copies the result into a management report. A small intervention could record the request, approval and status in one governed path. The baseline should capture how often information is re-entered, the waiting time for decisions and how frequently a coordinator has to resolve missing context. A pilot measures those same signals on comparable requests; it should not claim a universal saving merely because a form was replaced.",
  "The investment estimate must include connecting the new process to the existing purchasing record, migrating open requests where necessary, training approvers and supporting exceptions. If the report still requires manual export and correction, the intervention has not removed that part of the fragmentation. Leadership can decide whether a second phase is justified using evidence from the first, with uncertainty stated plainly.",
  "A successful pilot may still reveal a policy problem. If approvals stall because authority is unclear, automation can make the stall visible but cannot decide who should approve. Assign the decision owner and change the rule before scaling the technology. A credible business case follows the constraint even when the answer is not more software."
 ]},
 "operational-reporting-modernization": {sequence:[
  "Take one disputed management measure through a full review. Suppose operations counts a request as complete when work is finished, while finance counts it only after a formal acceptance event. Both reports may be correct within their own definitions. Identify the decision each serves, document the two states and determine whether leadership needs one shared measure or two explicitly labeled views. Changing a chart label without agreeing on the business rule will not restore trust.",
  "For the chosen measure, map the source events, identifiers, refresh cadence and known adjustments. Create a tested transformation, compare its output with the existing manual report and explain every material difference before retiring the old process. Publish an as-of time and identify the person who resolves exceptions. Then ask a reader to trace one reported value back to its source and definition. If the team cannot do that, the slice is not yet complete even if the dashboard looks polished.",
  "Use this first slice to decide architecture, not the other way around. If additional measures depend on the same history and cross-system joins, a governed shared model may reduce duplicated logic. If the next decision needs only a current operational status, a simpler projection may suffice. Expand according to recurring decision needs and support burden rather than platform fashion."
 ]}
};
