// Editorial expansion follows the section IDs in the shared final-Insights registry.
export const fintechDepth: Record<string, Record<string, string[]>> = {
  "fintech-what-to-outsource": {
    model: [
      "Start with decisions, not job titles. A startup might use external frontend engineers but retain internal ownership of its customer journey, acceptance rules and data-handling policy. Conversely, a specialist might help design a complex integration while an internal lead remains accountable for why that design fits the product. On a one-page map, put each workstream under Own, Extend or Delegate; beside it, write who approves scope, who accepts delivery and who can operate it after the engagement. If the answers are unclear, changing the contracting model will not resolve the underlying gap.",
      "The same capability can move between categories as the company grows. Early on, external engineers might help establish a cloud foundation while a founder holds architecture decisions with an experienced reviewer. Later, an internal platform lead may own those decisions directly. Revisit the map when the product acquires a new integration, a dependency becomes operationally critical or a team changes. The question is not whether a person is on the payroll; it is whether the company can explain, direct and sustain the work it considers strategic."
    ],
    ownership: [
      "Write down the states the product promises to customers. For an onboarding journey, that might mean who can mark identity verification complete, which system can reverse that status and what happens when evidence expires. For a payment journey, distinguish the customer's request from confirmation by an external provider. These definitions belong to the product's decision owners even if a partner implements the interfaces. When there is a dispute, the organization must be able to reconstruct which rule applied and who authorized any exception.",
      "Architecture governance need not become an approval meeting for every commit. Define the decisions that require review: changes to the authoritative record, handling of sensitive information, external-provider contracts, failure recovery and production access. Use a short decision record that describes the options, chosen boundary and rollback implications. The internal lead can then delegate ordinary implementation while retaining the ability to challenge a proposal that transfers an essential product dependency outside the company's control."
    ],
    extend: [
      "A useful extension has a working interface with the internal team: a shared backlog, named reviewer, test environment and definition of accepted work. Give engineers a representative first task rather than a vague promise of capacity. If the task is a provider integration, include test credentials, a sample failure response and the expected state after a delayed callback. If that context cannot be provided, the constraint may be product discovery rather than a shortage of engineers.",
      "Match the specialist to the actual bottleneck. More application developers will not fix a release process in which every change waits for a manual environment setup. A cloud specialist might remove the deployment dependency; a data engineer might repair a reporting handoff; a QA engineer might make acceptance reproducible. Ask what work will become possible for the existing team after the specialist leaves. That question turns capacity procurement into a capability decision rather than a permanent dependency."
    ],
    governance: [
      "Treat repository custody, intellectual-property terms and access as separate topics. Agree who owns the repository and infrastructure accounts, how third-party code and licenses are recorded, what deliverables can be reused and how access is revoked. Have the appropriate legal and security owners review terms. In day-to-day delivery, use named accounts, scoped permissions and a visible approval path for production changes. A contract that says ownership transfers is not enough if the client cannot build or deploy the result from accounts it controls.",
      "Make knowledge transfer observable. A runbook is useful only if someone other than its author can follow it. Ask the internal team to deploy a release, diagnose a representative failed integration and explain a key business rule while the partner is still available to correct gaps. Schedule those checks throughout delivery rather than in the final week. A workable exit includes access inventory, open defects, unfinished decisions, support responsibilities and a clear record of which services or credentials need rotation."
    ],
    proof: [
      "The published digital brokerage case study describes interconnected onboarding, identity, payments, trading, data and reporting capabilities. Use it to think about the breadth of decisions a connected financial product requires—not as evidence of any particular staffing arrangement. A founder could map each of those domains to a decision owner, an implementation team and an acceptance reviewer. The useful lesson is that one connected experience crosses several technical boundaries, and losing ownership at any boundary makes future product changes harder to reason about."
    ]
  },
  "fintech-asynchronous-workflows": {
    flow: [
      "A reliable workflow begins before a message reaches a queue. Record the business intent with a stable identifier and an initial state, then make the subsequent work discoverable and repeatable. Otherwise an accepted customer request may exist only in memory while a worker is waiting to run. Sketch the state transitions in plain language: accepted, awaiting provider, confirmed, rejected, requires investigation. For every transition, name the event or evidence that permits it and the team that can intervene when it stalls.",
      "Do not promise immediate completion when a third party has not confirmed it. An acknowledgement means the request was received; it is not the same as an external settlement or completed order. The interface should show a truthful intermediate state and a way for support to locate it. The choice of queue or event service is secondary to a recoverable record of what was requested, what has already happened and what may happen next."
    ],
    synchronous: [
      "Keep synchronous steps for decisions the caller genuinely needs before proceeding: authentication, input validation or determining whether the request can be accepted. Long-running processing and external callbacks can continue asynchronously, but the customer-facing journey still needs a response. Return a stable reference that can be used to check status. Agree whether the user may cancel, retry or edit while processing, and ensure the system enforces those rules rather than relying on button states alone.",
      "Design for the ambiguous timeout. If the client sees no response, it cannot know whether the server accepted the request. Its retry must carry the same business-intent identifier; the server must return the existing state if the request was already recorded. Testing only a clean success and a clean rejection misses the most important path: the action may have succeeded while the response was lost."
    ],
    idempotency: [
      "Idempotency means a repeated delivery of the same intent does not repeat its business effect. Define its scope explicitly: which customer, action, payload and period does one key represent? A matching key with changed payment details should not silently inherit the result of a different request. Store the identifier alongside the durable intent and return a consistent status for retries. Provider-side idempotency can help at an API boundary, but it does not replace protection of your own state transitions and records.",
      "Test duplicate arrival at several points: before work starts, while a worker is still processing, after a provider call succeeds and after notification fails. The correct response can differ at each stage. A duplicate might wait for the in-progress result; a post-completion retry should report the result already recorded; a failed notification may be retried without repeating the underlying financial action. This is why deduplication must be tied to the business operation, not only to queue delivery."
    ],
    failure: [
      "Classify failures before choosing retries. A temporary network error may warrant a bounded retry with delay; invalid account details require correction; an ambiguous provider timeout may require status lookup before any repeat; an unauthorized request must stop. Record the attempt and its response without treating every error as a new business request. A failed-processing queue is only useful if an operator can identify the intent, reason, last safe state and permitted recovery action.",
      "Event ordering matters. A later notification failure should not turn a confirmed transaction back into an unconfirmed one. Separate core business states from side effects and define transitions that cannot be reversed by a late callback. Where an external system can send messages out of order, compare event sequence or authoritative state rather than simply accepting the last message received. Recovery should restore the correct state, not merely clear a queue."
    ],
    reconcile: [
      "Reconciliation compares what the platform believes happened with evidence from other participants. Choose a stable reference shared across systems, define expected timing and put disagreements into named exception categories. A missing provider confirmation, a duplicate callback and a mismatch in amount need different investigation paths. Reconciliation is not a single nightly script; it is an operating responsibility with ownership, review cadence and a documented route for correcting records without hiding the original event.",
      "For support and engineering, connect logs, traces and business events through a correlation identifier while controlling access to sensitive details. A useful case view answers when a request was accepted, which stage last completed, what was attempted, what the provider returned and whether the current state has been reconciled. The brokerage case study documents connected platform and cloud/serverless processing capabilities; it is a relevant architectural context, not a claim about a specific undisclosed retry policy or transaction volume."
    ]
  },
  "fintech-data-engineering": {
    chain: [
      "Choose one management question and trace it back to a customer or product event. For example, if a team asks how many requests reached a particular status last month, define the event, authoritative record, effective date and exclusions before building a chart. Carry stable identifiers and timestamps through ingestion, validation and modeling. Without them, a polished report cannot distinguish a repeated message from a new event or explain why a historical total changed.",
      "A transactional system is optimized for recording operational changes. It is not necessarily the best place to combine several services' histories and definitions. Analytical models can support those questions without moving the source of operational authority. That separation makes it possible to improve a report while preserving the application contract, provided data movement, corrections and freshness are documented. It does not automatically require a warehouse: start from the reporting question and the number of sources involved."
    ],
    sources: [
      "Inventory ownership at the field level, not just the system level. One service may own the customer's onboarding status, another the payment provider reference and another the document used for verification. Note whether a field is a current snapshot, an immutable event, a derived status or a manually corrected value. A change to a status code upstream should trigger a review of downstream definitions. This is a better defense against contradictory dashboards than copying every available table into a single store.",
      "Ingestion needs a recovery contract: how do you detect missing batches, repeated events, late arrivals and schema changes? Capture the arrival time separately from the business event time; a delayed callback can describe an action that occurred earlier. Preserve enough raw context to reprocess a modeled result when a definition changes, subject to retention and access rules. Document which fields are sensitive and whether an analytical consumer needs them at all."
    ],
    reconcile: [
      "Validation asks whether the data obeys its own rules: identifiers present, relationships valid, statuses permitted and required fields complete. Reconciliation asks whether independent records agree. These are different controls. A transformed row can pass every schema test while still representing a provider event that never reached the internal account record. Assign exception categories, owners and a correction workflow rather than quietly filtering mismatches out of a report.",
      "Financial and management measures require explicit treatment of timing and definitions. Distinguish the event date from the date it entered the reporting model. If an adjustment is posted later, decide how the original period is represented and how a report consumer learns that a historical number changed. Do not assume a single generic P&L definition can be inferred from raw transactions; finance and product owners must approve the business rules appropriate to their own operation."
    ],
    models: [
      "Operational views and management analysis answer different questions. A support agent may need the current state of one request with a clear last-updated time. A leadership report may need a consistent, restatable comparison across periods and products. State the freshness contract for each. A fast but incomplete feed can be less useful for a periodic review than a slower reconciled model whose definitions can be reproduced. Real-time processing is justified by the decision, not by the availability of streaming technology.",
      "A data warehouse or modeled platform becomes useful when cross-system history, repeatable joins and shared definitions recur across teams. Start with a limited subject area and test one metric end to end before replicating every source. Record lineage: the source fields, transformations, tests, exception handling and report consumers. The brokerage and published data-engineering case studies offer context for connected platform and reporting capabilities; they do not establish any unpublished financial calculation or guaranteed outcome for another organization."
    ]
  }
};
