import type { ArticleSection, BatchArticle, AssessmentQuestion, InsightAssessment } from "./insights-batch";

// Batch 7 — Fintech growth, platform and integration cluster (21/30).
// Proof boundary: only structural capabilities published on /case-studies/digital-brokerage-platform.
const published = "2026-09-26";
const link = (label:string,to:string)=>({label,to});
const q = (key:string,prompt:string,options:[string,string,number][]):AssessmentQuestion=>({key,prompt,choices:options.map(([label,value,score])=>({label,value,score}))});
const tri=(key:string,prompt:string,a:string,b:string,c:string)=>q(key,prompt,[[a,"low",0],[b,"mid",1],[c,"high",2]]);
const end=[{id:"faq",label:"Frequently asked questions"},{id:"sources",label:"Research & Sources"}];
const toc=(sections:ArticleSection[])=>[...sections.map(({id,title})=>({id,label:title})),...end];

const fintech=link("Fintech product engineering","/industries/fintech");
const brokerage=link("Explore the Digital Brokerage Platform case study","/case-studies/digital-brokerage-platform");
const capacity=link("Engineering capacity","/solutions/engineering-capacity");
const software=link("Software engineering","/solutions/software-engineering");
const modernizationSolution=link("Application modernization","/solutions/application-modernization");
const cloud=link("Cloud & platform engineering","/solutions/cloud-platform-engineering");
const integrationSolution=link("API & system integration","/solutions/integration");
const staffPillar=link("Staff augmentation vs dedicated team vs outsourcing","/insights/staff-augmentation-vs-dedicated-team-vs-outsourcing");
const modernPillar=link("Application modernization: refactor, replatform, rebuild or replace","/insights/application-modernization-refactor-replatform-rebuild-replace");
const cloudArticle=link("Cloud migration vs cloud modernization","/insights/cloud-migration-vs-cloud-modernization");
const integrationPillar=link("System integration strategy","/insights/system-integration-strategy");
const dataArticle=link("Data engineering for growing businesses","/insights/data-engineering-growing-businesses");
const a19=link("How should a fintech scale engineering after funding?","/insights/fintech-scale-engineering-after-funding");
const a20=link("Fintech platform modernization","/insights/fintech-platform-modernization");
const a21=link("Fintech API & integration strategy","/insights/fintech-api-integration-strategy");

const sources={
  dora:{name:"DORA (Google Cloud)",year:"2024",title:"Accelerate State of DevOps Report",url:"https://dora.dev/research/",note:"Research on software delivery performance and the capabilities associated with it. Used for delivery-capability concepts only; no Xyncwave outcome is inferred."},
  topologies:{name:"Team Topologies",year:"2026",title:"Key concepts: team types and interaction modes",url:"https://teamtopologies.com/key-concepts",note:"A reference model for team boundaries and cognitive load; consulted for ownership concepts, not as an endorsement of a specific structure."},
  codeowners:{name:"GitHub Docs",year:"2026",title:"About code owners",url:"https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners",note:"Documentation for assigning review ownership in repositories; an example of a governance mechanism, not a requirement."},
  fsiLens:{name:"AWS",year:"2026",title:"Financial Services Industry Lens — AWS Well-Architected Framework",url:"https://docs.aws.amazon.com/wellarchitected/latest/financial-services-industry-lens/financial-services-industry-lens.html",note:"Architecture guidance for financial-services workloads. Referenced for design considerations; it does not imply certification or compliance."},
  strangler:{name:"Microsoft Learn",year:"2026",title:"Strangler Fig pattern",url:"https://learn.microsoft.com/en-us/azure/architecture/patterns/strangler-fig",note:"An incremental migration pattern for replacing selected capabilities while the existing system continues to operate."},
  acl:{name:"Microsoft Learn",year:"2026",title:"Anti-corruption Layer pattern",url:"https://learn.microsoft.com/en-us/azure/architecture/patterns/anti-corruption-layer",note:"A pattern for isolating an application from the models and semantics of external systems."},
  sqs:{name:"AWS Documentation",year:"2026",title:"What is Amazon Simple Queue Service?",url:"https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/welcome.html",note:"Documentation of queue-based decoupling, retries and dead-letter handling; an example technology, not a recommendation for every platform."},
  otel:{name:"OpenTelemetry",year:"2026",title:"OpenTelemetry documentation",url:"https://opentelemetry.io/docs/",note:"Vendor-neutral concepts for traces, metrics, logs and context propagation across services."},
  oidc:{name:"OpenID Foundation",year:"2014",title:"OpenID Connect Core 1.0",url:"https://openid.net/specs/openid-connect-core-1_0.html",note:"The identity layer on top of OAuth 2.0; referenced for token-based identity concepts only."},
  retry:{name:"Microsoft Learn",year:"2026",title:"Retry pattern",url:"https://learn.microsoft.com/en-us/azure/architecture/patterns/retry",note:"Guidance on handling transient failures, including the need for idempotent operations when retrying."},
  idempotency:{name:"Stripe Docs",year:"2026",title:"Idempotent requests",url:"https://docs.stripe.com/api/idempotent_requests",note:"A public example of how one payment API uses idempotency keys to make retries safe. Illustrative only; no provider relationship is implied."},
};

/* ---------------- Article 19 ---------------- */
const scaleSections:ArticleSection[]=[
{id:"roadmap-outpaces-team",title:"Funding changes the roadmap faster than the team",answer:"A funding round usually accelerates commitments before it accelerates delivery capacity. The roadmap changes in weeks; hiring, onboarding and architecture change in months.",paragraphs:["After a raise, the product plan often becomes more ambitious at once. Investors expect progress against the plan that justified the round. Sales conversations move toward larger customers who ask for integrations, security reviews and reporting. The product team may want to expand into new features or channels. Engineering is asked to deliver more of everything, sooner.","Not every funded fintech experiences all of the following, but these pressures are common: an accelerated roadmap, enterprise customer commitments, new third-party integrations, product expansion, a new geography, infrastructure and reliability work, new data and reporting requirements, and several open engineering vacancies at the same time.","Funding creates options. It does not create an obligation to convert every requirement into permanent headcount as fast as possible. The first executive decision is not how many engineers to hire; it is what kind of capacity each piece of work actually needs."]},
{id:"is-capacity-the-problem",title:"First determine whether capacity is actually the problem",answer:"Slow delivery is not always a headcount problem. Before adding people, confirm whether the constraint is capacity, architecture, skills, dependencies, priorities, testing, deployment or integration complexity.",paragraphs:["If every change requires coordinated edits across several services, more engineers may simply mean more coordination. If releases wait for a manual regression cycle, the bottleneck is testing. If the team is building three things the business has not ranked, the issue is prioritization. These problems look the same from the outside—\"engineering is slow\"—but need different answers."],bullets:["Insufficient engineering capacity for a clearly prioritized backlog","Architecture constraints that make small changes expensive","A specific skill gap, such as cloud, data or a financial integration","External dependencies on providers, partners or other teams","Unclear or frequently changing priorities","A testing or QA bottleneck","A fragile or manual deployment process","Integration complexity with payment, identity or data providers"],links:[a20]},
{id:"capacity-map",title:"The Fintech Engineering Capacity Map",variant:"framework",answer:"Place each workstream on two dimensions—how long the need lasts and how much responsibility the work carries—to see which capacity model fits.",paragraphs:["This is a Xyncwave directional decision framework, not a formula. Duration of need runs from temporary to ongoing. Scope of responsibility runs from a specialist task to a full workstream or strategic ownership. Different positions suggest different models.","Specialist augmentation fits shorter needs for a specific skill. An engineering pod fits an ongoing or substantial workstream that still runs under internal leadership. A project team fits a defined project where an external team carries greater delivery ownership. A permanent hire fits long-term product ownership and strategic capability. Internal reprioritization applies when the capacity already exists but is pointed at the wrong work."]},
{id:"stay-internal",title:"What should stay internal?",answer:"Keep ownership of product strategy, core architecture decisions, security accountability, domain knowledge and long-term technical direction inside the company. That does not mean all code must be written internally.",paragraphs:["Ownership and execution are different. A company can own the product direction and architecture while external engineers implement parts of it under internal review. What becomes risky is outsourcing the judgment: who decides how the platform evolves, who understands why a financial workflow behaves the way it does, and who is accountable for security decisions.","A useful test is to ask what happens if the external capacity leaves in six months. If the company would lose the ability to explain or change its own platform, too much ownership has moved outside."],bullets:["Product strategy and prioritization","Product ownership for customer-facing workflows","Core architecture decisions and technical governance","Security ownership and access decisions","Domain knowledge of financial workflows and obligations","Long-term technical direction"]},
{id:"permanent-hiring",title:"When permanent hiring makes sense",paragraphs:["Hire permanently when the capability will be needed indefinitely and is central to how the company competes. Engineering leadership, product-facing engineers who hold domain context, and platform owners usually fall here. So do roles that accumulate knowledge the business cannot easily transfer.","Permanent hiring is slower and harder to reverse. That is not a reason to avoid it; it is a reason to reserve it for the capabilities where continuity matters most."],bullets:["Ongoing core capability the product depends on","Long-term ownership of a domain or service","Engineering and technical leadership","Deep domain knowledge of financial workflows","Business-critical internal competency"]},
{id:"external-capacity",title:"When external engineering capacity makes sense",paragraphs:["External capacity is useful when the need is real but its shape is temporary, specialized or bounded. It can also bridge the months while permanent hiring catches up. It is not universally superior: it works when internal leadership can direct it, and it adds risk when it substitutes for missing ownership."],bullets:["A temporary delivery spike tied to a launch or customer commitment","A defined workstream with clear boundaries","A specialist skill the team needs for a period, not permanently","An integration backlog with several providers","Modernization work alongside ongoing product delivery","A release deadline that current capacity cannot meet","Permanent hiring that is taking longer than the roadmap allows"]},
{id:"core-extend-deliver",title:"Core / Extend / Deliver",variant:"framework",answer:"Sort work into three categories: what the company must own, where it needs more engineering around internal leadership, and what an external team can deliver as a bounded project.",subsections:[{title:"Core — keep strategic ownership internally",paragraphs:["Decisions and knowledge the company cannot hand over without weakening its product."],bullets:["Product direction","Architecture governance","Domain ownership"]},{title:"Extend — add capacity around internal leadership",paragraphs:["External engineers work inside the company's repositories, rituals and review process, directed by internal leads."],bullets:["Backend","Frontend","QA","Cloud","Data","Integrations"]},{title:"Deliver — a bounded project with governance",paragraphs:["An external team owns delivery of a clearly scoped project or workstream, with agreed acceptance criteria, reviews and handover."],bullets:["Defined scope and outcomes","Regular architecture review","Documented handover"]}]},
{id:"specialist-pod-project",title:"Specialist vs pod vs project team in a growth-stage fintech",answer:"Match the model to the fintech situation, not to a generic preference. The broader commercial comparison sits in the staff augmentation pillar; this table focuses on post-growth fintech scenarios.",table:{headers:["Situation","Specialist augmentation","Engineering pod","Project team"],rows:[["New payment or data provider integration","Good fit if the team lacks that integration skill","Fit if several integrations are queued","Fit if the integration is a separable project"],["Enterprise customer requirements (SSO, reporting)","Useful for a specific skill such as identity","Fit for a sustained stream of requirements","Fit if the scope is fixed and time-bound"],["Cloud or DevOps maturity work","Often a specialist need","Fit when it becomes ongoing platform work","Fit for a defined migration or setup"],["Core product feature roadmap","Limited—context-heavy work","Fit under internal product ownership","Rarely appropriate for core product"],["Modernization alongside delivery","Fit for targeted upgrades","Fit for a sustained modernization stream","Fit for a bounded extraction or rebuild"]]},links:[staffPillar]},
{id:"product-ownership",title:"Protecting product ownership with external engineers",answer:"Ownership is protected by governance mechanisms, not by who writes the code.",bullets:["Repositories stay in company-controlled accounts","Internal architectural oversight for significant design decisions","Code review by internal engineers or designated owners","Documentation as part of the definition of done","Clear intellectual-property terms in the engagement","Least-privilege access management, reviewed and revoked on exit","A planned handover rather than an abrupt end","Named internal technical leadership for every external stream"]},
{id:"velocity-without-chaos",title:"Delivery velocity without delivery chaos",answer:"Adding developers can slow delivery when onboarding is poor, architecture is unclear, teams overlap, requirements are weak or deployment is fragile.",paragraphs:["New engineers consume attention before they add output. If the architecture is only understood by two people, those two people become the bottleneck. If two teams edit the same service without clear boundaries, merges and regressions multiply. If requirements arrive as one-line tickets, engineers build the wrong thing faster. If each release needs a careful manual deployment, more code means more risk per release.","Before scaling, invest a little in the things that let more people work safely: a documented architecture overview, clear service or module ownership, a reliable CI/CD pipeline, a testable definition of done and a realistic onboarding plan."]},
{id:"in-practice",title:"What this looks like in real platform engineering",variant:"proof",paragraphs:["Xyncwave's anonymized Digital Brokerage Platform case study is not a story about scaling a funded startup. It is useful here for another reason: it shows the breadth of technical work that extended engineering capability may need to cover on a fintech platform.","The published case describes work across digital client onboarding, authentication and identity, payment and third-party integrations, cloud and serverless services, databases and reporting, multi-asset trading workflows and production troubleshooting with release coordination. Any team extending a fintech platform should be able to work across these boundaries, under the platform owner's governance."],links:[brokerage,capacity,software]},
];
const scaleAssessment:InsightAssessment={title:"Fintech Engineering Capacity Planner",intro:"Describe the workstream and your team. See a directional capacity model before sharing any contact details.",leadType:"engineering",cta:"Review Your Engineering Capacity",context:{industry:"Fintech",solutionInterest:"Engineering Capacity"},disclaimer:"A directional planning aid. Validate the workstream, architecture and ownership model before committing to hiring or an engagement.",questions:[
 tri("size","What is your current engineering team size?","Fewer than 5 engineers","5–20 engineers","More than 20 engineers"),
 tri("roadmap","How much roadmap work is waiting beyond current capacity?","A little","A noticeable backlog","Much more than the team can deliver"),
 tri("workstreams","How many active workstreams compete for the same engineers?","One or two","Three or four","Five or more"),
 q("skills","Is a specific specialist skill missing?",[["No, we have the skills","none",1],["Yes, one specific skill","one",0],["Several skills for a whole stream","many",2]]),
 tri("hiring","How long is permanent hiring taking?","Roles fill quickly","A few months","Longer than the roadmap allows"),
 tri("deadline","How firm is the next product deadline?","Flexible","Important","Committed to customers or investors"),
 q("architecture","How clear is the architecture for new engineers?",[["Clear and documented","clear",2],["Partly documented","partial",1],["We are not sure","unknown",0]]),
 tri("leadership","How much internal technical leadership can direct extra engineers?","Very little","Some","Strong leads with capacity"),
 q("duration","How long will this need last?",[["A few months","short",0],["Six to eighteen months","medium",2],["Indefinitely — core capability","ongoing",1]]),
 q("ownership","Where should delivery ownership sit?",[["Fully internal, long term","internal",0],["Internal leads with extra engineers","extend",1],["An external team for a bounded project","deliver",3]]),
 q("cause","What best explains slow delivery today?",[["Not enough people for clear priorities","capacity",2],["Priorities keep changing","priorities",0],["We have not diagnosed it","unknown",0]]),
],overrides:[{key:"cause",value:"priorities",result:"Internal reprioritization first"},{key:"duration",value:"ongoing",result:"Permanent hiring should be evaluated"},{key:"skills",value:"one",result:"Specialist augmentation candidate"}],unknownResult:{value:"unknown",minimum:2,result:"Delivery diagnosis required"},results:[
 {min:0,title:"Internal reprioritization first",body:"The constraint may be focus rather than headcount. Ranking and reducing concurrent work could release capacity faster than hiring.",actions:["Rank active workstreams by business consequence","Pause or stop the lowest-value stream"]},
 {min:9,title:"Specialist augmentation candidate",body:"A specific skill gap for a bounded period suggests adding one or two specialists inside your existing team and process.",actions:["Define the skill and expected duration","Assign an internal owner for review and handover"]},
 {min:14,title:"Engineering pod candidate",body:"A substantial, continuing workstream with internal leadership suggests a small cross-functional pod working inside your governance.",actions:["Define the workstream boundary and outcomes","Set code review, access and documentation rules"]},
 {min:20,title:"Project-team candidate",body:"A defined, separable piece of work may suit an external team that owns delivery against agreed acceptance criteria and handover.",actions:["Write down scope, interfaces and acceptance criteria","Agree architecture reviews and a handover plan"]},
 {min:999,title:"Permanent hiring should be evaluated",body:"An indefinite need for a core capability usually argues for permanent ownership. External capacity may still bridge the hiring period.",actions:["Identify which roles hold long-term domain knowledge","Use temporary capacity only as a bridge"]},
 {min:999,title:"Delivery diagnosis required",body:"The cause of slow delivery is not yet clear. Diagnose architecture, testing, deployment and priorities before choosing a capacity model.",actions:["Trace one recent feature from idea to release","Note where it waited and why"]},
]};

/* ---------------- Article 20 ---------------- */
const modernSections:ArticleSection[]=[
{id:"growth-exposes-architecture",title:"Product growth can expose architecture constraints",answer:"Product growth and architecture growth are different things. A platform that fitted the first product can start resisting the second, third and fourth.",paragraphs:["Early fintech platforms are built to launch one proposition well. Growth then adds new financial products, enterprise requirements, new payment flows, additional data providers, stronger identity requirements, more third-party integrations and more customer channels. Each change is reasonable. Together they can push the platform beyond the shape it was designed for.","The Fintech Platform Pressure Map below is a Xyncwave way of seeing where that stress accumulates. It is not a scientific benchmark: it helps leadership see whether several pressures are converging at once."]},
{id:"pressure-map",title:"The Fintech Platform Pressure Map",variant:"framework",answer:"Modernization becomes more relevant as several of six pressures converge—not because any one of them exists.",subsections:[{title:"Product pressure",paragraphs:["New features, products and channels that the current structure makes expensive to add."]},{title:"Integration pressure",paragraphs:["More providers, APIs and external systems, each with its own behaviour."]},{title:"Transaction pressure",paragraphs:["Increasing workflow complexity: more states, steps and exceptions per customer action."]},{title:"Delivery pressure",paragraphs:["Release frequency and deployment complexity that raise the risk of each change."]},{title:"Operational pressure",paragraphs:["Troubleshooting, incidents and observability gaps that slow diagnosis."]},{title:"Data pressure",paragraphs:["Reporting, reconciliation and analytics that depend on tightly coupled transactional data."]}]},
{id:"warning-signs",title:"Signs the platform is becoming the constraint",answer:"The clearest sign is when required product change becomes disproportionately expensive or risky compared with its size.",bullets:["A small feature requires many coordinated changes","Every release touches multiple systems","Failures are difficult to trace across services","Third-party integration details leak into customer-facing code","Synchronous request paths contain long-running work","Deployment risk is increasing with each release","An older framework or runtime limits necessary change","Database logic is tightly coupled across unrelated features"],paragraphs:["These are general signals, not a description of any particular client platform. One sign alone is rarely a reason to modernize. Several signs appearing together, and slowing the roadmap, deserve an assessment."]},
{id:"modernize-constraint",title:"Modernize the Constraint",variant:"framework",answer:"Ask five questions in order and modernize the part that fails, not the whole platform.",table:{headers:["Question","If yes","If no"],rows:[["Does the business requirement still fit the capability?","Continue","Evaluate replacement or rebuild of that capability"],["Does the architecture still support required change?","Continue","Refactor or extract a service"],["Is the platform/runtime supportable?","Continue","Upgrade or replatform"],["Is integration complexity manageable?","Continue","Modernize the integration boundary"],["Are deployment and operations sustainable?","Maintain","Invest in delivery pipeline and observability"]]},paragraphs:["Possible actions include maintain, upgrade, refactor, replatform, extract a service, modernize an integration boundary, rebuild a selected capability or evaluate replacement. The general methodology behind each path is covered in the application modernization pillar."],links:[modernPillar]},
{id:"framework-modernization",title:"Framework and runtime modernization",paragraphs:["Supported runtimes and maintained dependencies matter because they receive security fixes and remain compatible with the libraries and cloud services the platform needs. Upgrades should be planned: map dependencies, check compatibility, and build test coverage around the behaviour that must not change before moving versions.","Technology age alone is not a justification. A stable, supported component that does its job does not need replacing because a newer option exists. Modernize when the runtime blocks required change, loses support or creates avoidable operational risk."]},
{id:"api-boundaries",title:"API boundaries keep complexity where it belongs",answer:"Clear service and integration boundaries stop external-provider logic spreading across the application.",paragraphs:["When each part of the product calls a payment or data provider directly, provider-specific formats, errors and quirks appear in many places. Changing or adding a provider then becomes a platform-wide change. A defined boundary—an internal API or integration layer—lets the rest of the platform work with one consistent model.","Boundaries also reduce duplicated integration code and fragile frontend dependencies, because customer-facing applications depend on stable internal contracts instead of external ones."],links:[a21]},
{id:"async-processing",title:"Event-driven and asynchronous processing",answer:"Work that is long-running, retriable or not needed for the immediate response is often better decoupled from the customer request.",paragraphs:["A representative asynchronous pattern: the customer or API request receives immediate processing and a clear acknowledgement; the remaining work is placed on a queue or event path; a background worker processes it with retries; and downstream systems are updated when it completes. Notifications, document processing, provider callbacks and reporting updates are typical candidates.","Asynchronous design introduces its own responsibilities: retries must not duplicate actions, failures need a visible home such as a dead-letter queue, and the customer experience must represent in-progress states honestly."],bullets:["Customer / API request","Immediate validation and acknowledgement","Queue or event path","Background worker with retries","Downstream update and notification"]},
{id:"identity-evolution",title:"Identity and authentication evolution",paragraphs:["As products and channels multiply, separate login mechanisms become a source of friction and risk. Centralized identity with token-based access lets web, mobile and partner channels authenticate consistently and allows authentication to work across products.","Migrating identity is a coordination exercise: existing sessions, user records, channels and support processes must move without locking customers out. Plan it as a staged change with rollback, not as a configuration switch."]},
{id:"observability",title:"Observability is part of modernization",answer:"Modernization is not only architecture. It also improves how the platform can be operated.",paragraphs:["When a customer action crosses several services and providers, troubleshooting depends on being able to follow it. Structured logs, audit trails, explicit failure states, correlation identifiers carried across services, service-level monitoring and actionable alerts turn incidents from investigations into diagnoses.","A platform with clear observability can often be changed more confidently, because the team can see the effect of each release."],bullets:["Structured logs","Audit trails for significant actions","Explicit failure states","Correlation across services","Service monitoring","Actionable alerts"]},
{id:"data-reporting",title:"Data and reporting considerations",paragraphs:["A platform may also be constrained by its data: reporting logic embedded in transactional code, databases shared by unrelated features, manual reconciliation and growing analytical requirements. Separating operational and analytical workloads, and making data flows explicit, can relieve pressure on the core platform."],links:[dataArticle]},
{id:"in-practice",title:"What this looks like in practice",variant:"proof",paragraphs:["Xyncwave's anonymized Digital Brokerage Platform case study documents engineering across serverless services, asynchronous workflows, centralized identity, third-party integrations, databases, observability and release coordination. These are examples of the engineering concerns involved in operating and evolving a complex fintech platform.","The case study does not describe a complete modernization programme, and none is implied here. Its relevance is the set of architectural concerns it covers."],links:[brokerage,cloud]},
{id:"rebuild-not-default",title:"Rebuild is not the default",answer:"Full rewrites should require strong justification. Preserve working business capability where practical and change the constraint.",bullets:["Functional regression in behaviour nobody documented","Migration complexity for data, users and integrations","A product freeze while the new platform catches up","Duplicated effort maintaining two systems","Hidden business logic discovered late","A risky production transition"],paragraphs:["Incremental approaches—extracting one capability at a time and routing traffic gradually—usually keep the product moving while the architecture improves."],links:[modernPillar,cloudArticle,modernizationSolution]},
];
const modernAssessment:InsightAssessment={title:"Fintech Platform Modernization Assessment",intro:"Rate the platform's delivery, architecture and operations. See a directional result before sharing contact details.",leadType:"digitalization",cta:"Review Your Fintech Platform",context:{industry:"Fintech",solutionInterest:"Application Modernization"},disclaimer:"Directional only. A platform decision needs code, architecture and operational review.",questions:[
 tri("release","How difficult is a typical release?","Routine","Needs coordination","High-risk and slow"),
 tri("framework","Are frameworks and runtimes supported?","Current and supported","Some ageing parts","Unsupported components"),
 q("coupling","How coupled is the architecture?",[["Clear modules or services","low",0],["Some tangled areas","mid",1],["Small changes touch many parts","high",2],["We are not sure","unknown",1]]),
 q("integrations","How is provider-specific logic handled?",[["Behind a clear boundary","bounded",0],["Partly isolated","partial",1],["Spread through the application","leaking",2]]),
 tri("deployment","How mature is deployment?","Automated pipeline","Partly automated","Mostly manual"),
 q("observability","Can you trace a failed customer action?",[["Yes, end to end","good",0],["Partly","partial",1],["Rarely","none",2]]),
 tri("async","Do long-running tasks run inside customer requests?","No","Some","Often"),
 tri("database","How coupled is the database?","Clear ownership","Some shared tables","Heavily shared across features"),
 q("incidents","How long does incident troubleshooting take?",[["Quick to diagnose","fast",0],["Hours","slow",1],["Hard to know where to look","unknown",2]]),
 tri("roadmap","How much is architecture limiting the roadmap?","Not at all","Somewhat","Significantly"),
],overrides:[{key:"integrations",value:"leaking",result:"Integration modernization priority"},{key:"observability",value:"none",result:"Delivery/observability gap"}],unknownResult:{value:"unknown",minimum:2,result:"Architecture discovery required"},results:[
 {min:0,title:"Stable platform",body:"The platform appears able to support current change. Keep dependencies current and monitor the pressures as the roadmap grows.",actions:["Review runtime support annually","Watch release effort and incident trends"]},
 {min:7,title:"Targeted modernization candidate",body:"Specific areas are creating friction. Modernize the constraint—an upgrade, a refactor or an extracted service—rather than the whole platform.",actions:["Identify the two most expensive change areas","Plan a bounded, testable improvement"]},
 {min:13,title:"Delivery/observability gap",body:"Release risk and diagnosis may be slowing the roadmap more than architecture. Invest in pipelines, correlation and alerts first.",actions:["Automate the release path","Add correlation IDs and actionable alerts"]},
 {min:17,title:"Selective re-architecture candidate",body:"Several pressures appear to converge. Re-architect selected capabilities incrementally while the platform keeps operating.",actions:["Map pressures to specific capabilities","Sequence extraction with rollback plans"]},
 {min:999,title:"Integration modernization priority",body:"Provider-specific logic spread across the application makes every change harder. A clearer integration boundary is likely the first move.",actions:["Inventory providers and where they are called","Design one internal contract per domain"]},
 {min:999,title:"Architecture discovery required",body:"Too much is unknown to choose a path. A short architecture discovery should come before any modernization decision.",actions:["Document services, data and dependencies","Trace one critical workflow end to end"]},
]};

/* ---------------- Article 21 ---------------- */
const integrationSections:ArticleSection[]=[
{id:"integration-products",title:"Why fintech products are integration products",answer:"A customer may see one application, but the experience depends on how identity, payment, data, execution, compliance and reporting systems coordinate behind it.",paragraphs:["Behind a single fintech app there can be identity systems, payment providers, market and financial data vendors, exchanges or execution venues, document and verification services, internal databases and reporting services. Each has its own data model, availability and failure behaviour.","APIs are the mechanism for connecting them. They are not the strategy. The strategy decides which systems participate in each workflow, which system owns each state, what data moves, how failures are handled and where provider-specific logic lives. The general enterprise approach is covered in the system integration strategy pillar; this article focuses on the financial ecosystem."],links:[integrationPillar]},
{id:"integration-map",title:"The Fintech Integration Map",variant:"framework",answer:"For every connection around the platform, answer three questions: what moves, who owns the state, and what happens if it fails.",subsections:[{title:"Identity & verification",paragraphs:["Moves identity attributes and verification outcomes. The identity service owns authentication state."]},{title:"Payments",paragraphs:["Moves payment instructions and status. The provider owns processing state; the platform owns the customer-facing record."]},{title:"Market / financial data",paragraphs:["Moves prices, reference and fundamental data. The platform owns the normalized model it shows customers."]},{title:"Trading / execution",paragraphs:["Moves orders and acknowledgements. The execution system owns execution state; the platform owns positions it records."]},{title:"Compliance / documents",paragraphs:["Moves documents, signatures and checks. Ownership of each check must be explicit."]},{title:"Portfolio / reporting",paragraphs:["Moves derived records for statements and reports. Depends on reconciled upstream state."]},{title:"Internal data / operations",paragraphs:["Moves operational records to support, finance and analytics teams."]}]},
{id:"provider-boundary",title:"Keep external-provider complexity out of customer-facing applications",answer:"A middleware or internal API layer can absorb provider differences so web and mobile applications depend on stable internal contracts.",bullets:["Provider abstraction behind a consistent internal model","Normalized responses and error handling","Central validation before requests leave the platform","One place to monitor provider behaviour","Easier future provider substitution","Reduced frontend coupling to external APIs"],paragraphs:["Middleware is not mandatory for every architecture. A small product with one provider may not need it. It becomes more valuable as providers, channels and workflows multiply."]},
{id:"reliability-chain",title:"The Fintech Integration Reliability Chain",variant:"framework",answer:"Authenticate → Validate → Send → Acknowledge → Process → Persist → Confirm → Reconcile → Observe.",paragraphs:["This is a reasoning model, not a mandatory protocol. The exact stages vary by workflow. Its purpose is to make each step explicit so the team can ask what happens if that step fails: is the request retried, is the customer told, is the state marked as pending, and who is alerted?"]},
{id:"identity",title:"Identity integration",paragraphs:["Identity sits at the start of almost every financial workflow. Centralized authentication, well-managed sessions and token-based access allow web, mobile and partner channels to behave consistently. Verification outcomes from external identity services should be recorded with their source and time so later decisions can be explained. Implementation specifics belong to a security design, not a general article."]},
{id:"payments",title:"Payment integration",answer:"A frontend \"success\" screen is not the same as end-to-end financial consistency.",paragraphs:["A payment lifecycle typically runs: initiate, external processing, response, internal state update, transaction recording and reconciliation. Provider responses may be delayed, arrive by callback or change later. The platform should represent pending states honestly and treat confirmation and reconciliation as separate steps from the customer's click."],bullets:["Initiate","External processing","Response or callback","Internal state update","Transaction recording","Reconciliation"]},
{id:"market-data",title:"Market and financial-data integration",paragraphs:["Platforms often combine several data providers for prices, reference data and fundamentals. Providers differ in identifiers, formats, timing and coverage. Normalizing and validating data behind a provider abstraction gives customers one consistent model and lets the platform add or replace sources without rewriting screens."]},
{id:"trading",title:"Trading and execution integration",paragraphs:["At a high level, an order moves through request, validation, the execution system, acknowledgement, execution outcome, portfolio or position update and reporting. Each hand-off can succeed, fail or remain pending, and the platform must know which. This article describes system coordination only; it does not address trading strategy or offer financial advice."],bullets:["Order request","Validation","Execution system","Acknowledgement","Execution outcome","Portfolio / position update","Reporting"]},
{id:"documents",title:"Document and verification integrations",paragraphs:["Onboarding may involve KYC-related systems, eSign or document providers, bank-account verification and identity workflows. The integration concern is to know which provider performed which check, what the outcome was and where evidence is stored. Regulatory obligations remain the responsibility of the regulated business and its advisers."]},
{id:"sync-async",title:"Synchronous vs asynchronous integrations",answer:"Use synchronous calls when the customer needs an immediate answer and asynchronous patterns when work is long-running, retriable or driven by external status.",table:{headers:["Need","Likely pattern"],rows:[["Immediate validation","Synchronous API"],["Long-running or retriable work","Asynchronous queue or event"],["External status update","Callback, webhook or event"],["Reporting and analytics","Pipeline or batch"],["High-value state reconciliation","Explicit reconciliation workflow"]]},paragraphs:["This mapping is directional. Real workflows often combine patterns."]},
{id:"idempotency",title:"Idempotency and duplicate prevention",answer:"A retry should never accidentally create the same financial action twice.",paragraphs:["Networks time out and providers respond late, so retries are normal. Idempotency means the same request, sent more than once, has the same effect as sending it once. In practice this usually involves a stable request identifier that both sides recognize, and checks before creating a new record or instruction. Many payment providers publish their own idempotency mechanisms; the platform's internal services need the same discipline."]},
{id:"reconciliation",title:"Reconciliation",answer:"Internal and external records can disagree temporarily. Reconciliation verifies that they agree in the end—and flags when they do not.",paragraphs:["Reconciliation compares the expected state, the recorded state and the external confirmation, and identifies missing or duplicate conditions. It matters most in payments, trading, reporting and verification, where a silent mismatch can surface later as a customer complaint or a reporting error. Design it as a routine workflow with owners, not as an emergency script."]},
{id:"observability",title:"Integration observability",bullets:["Request and correlation IDs across services and providers","Explicit status for each step","Structured logs","Recorded external responses","Retry counts and outcomes","Actionable alerts","An audit trail for significant actions"],paragraphs:["When a customer asks where their payment or order is, the team should be able to answer from the platform, not by searching several vendor dashboards."]},
{id:"in-practice",title:"What this looks like in practice",variant:"proof",paragraphs:["Xyncwave's anonymized Digital Brokerage Platform case study documents middleware connecting digital applications with exchanges, payment providers, market and fundamental-data providers and other third parties, alongside identity integrations, internal databases and reporting. It is evidence of experience with the integration concerns described here, within the anonymized boundary of the published case."],links:[brokerage,integrationSolution,cloud]},
];
const integrationAssessment:InsightAssessment={title:"Fintech Integration Complexity Mapper",intro:"Describe your providers, workflows and failure handling. See a directional result before sharing contact details.",leadType:"digitalization",cta:"Map Your Fintech Integrations",context:{industry:"Fintech",solutionInterest:"API & System Integration"},disclaimer:"Directional only; not a security, compliance or architecture audit.",questions:[
 tri("providers","How many external providers does the platform depend on?","One to three","Four to eight","More than eight"),
 tri("identity","How many identity or verification systems are involved?","One","Two","Three or more"),
 tri("payments","How many payment providers or rails?","None or one","Two","Three or more"),
 tri("data","How many market or financial-data vendors?","None or one","Two","Three or more"),
 tri("execution","Are execution or exchange systems integrated?","No","One","Several"),
 q("reconcile","How is reconciliation handled?",[["Automated with owners","auto",0],["Partly automated","partial",1],["Mostly manual or ad hoc","manual",2]]),
 tri("async","How much work depends on callbacks or asynchronous status?","Little","Some","Most workflows"),
 q("exposure","Where does provider-specific logic live?",[["Behind a middleware or API layer","bounded",0],["Partly isolated","partial",1],["Inside customer-facing apps","exposed",2]]),
 q("observability","Can you trace a request across providers?",[["Yes","good",0],["Partly","partial",1],["No","none",2]]),
 tri("failure","How are provider failures handled?","Defined retries and alerts","Case by case","Discovered by customers"),
 q("state","Is ownership of each workflow state defined?",[["Yes","clear",0],["For some workflows","partial",1],["We are not sure","unknown",2]]),
],overrides:[{key:"reconcile",value:"manual",result:"Reconciliation gap"},{key:"observability",value:"none",result:"Observability gap"}],unknownResult:{value:"unknown",minimum:1,result:"Integration architecture discovery recommended"},results:[
 {min:0,title:"Low integration complexity",body:"The current integration landscape appears manageable. Document state ownership now so it stays that way as providers grow.",actions:["Record what moves, who owns state and failure behaviour","Revisit when adding a provider"]},
 {min:8,title:"Integration boundary needed",body:"Provider logic and workflows are growing. A clearer internal boundary could keep that complexity out of customer-facing applications.",actions:["Define internal contracts per domain","Isolate provider formats and errors"]},
 {min:15,title:"Middleware/orchestration candidate",body:"Many providers and asynchronous workflows suggest a middleware or orchestration layer with central validation, retries and monitoring.",actions:["Map the reliability chain for one workflow","Design idempotency and retry rules"]},
 {min:999,title:"Reconciliation gap",body:"Manual reconciliation leaves room for silent mismatches between internal and external state. Make it an owned, routine workflow.",actions:["List the states that must agree","Automate comparison and exception queues"]},
 {min:999,title:"Observability gap",body:"Without cross-provider tracing, incidents are slow to diagnose and customer questions hard to answer.",actions:["Add correlation IDs across calls","Record external responses and retries"]},
 {min:999,title:"Integration architecture discovery recommended",body:"State ownership is unclear. Map the workflows and owners before adding another connection.",actions:["Trace one payment or order end to end","Name the owner of each state"]},
]};

const scale:BatchArticle={slug:"fintech-scale-engineering-after-funding",cluster:"Fintech · Engineering Capacity",title:"Your Fintech Just Raised Funding: How Should You Scale Engineering Without Overhiring?",seoTitle:"How Should a Fintech Scale Engineering After Funding? | Xyncwave",metaDescription:"A practical framework for fintech founders and CTOs increasing engineering capacity after funding without prematurely expanding permanent headcount.",excerpt:"Separate strategic capability from temporary capacity, specialist gaps and bounded projects before converting a raise into headcount.",read:"17 min",published,modified:published,directQuestion:"How should a fintech scale engineering after funding?",directAnswer:"A funding round does not automatically mean every engineering requirement should become a permanent hire. Start by separating long-term strategic capability from temporary capacity, specialist skill gaps and defined projects. Keep product ownership, architecture and domain knowledge internal; then decide whether each remaining workstream needs a permanent hire, a specialist, an engineering pod or a bounded project team. Confirm first that people are actually the bottleneck—architecture, priorities or deployment may be.",takeaways:["Funding creates options, not an obligation to maximize headcount.","Protect internal ownership of product and architecture.","Separate temporary capacity from permanent capability.","Identify whether the bottleneck is actually people.","Specialist needs and full workstreams require different models.","External capacity should increase delivery capability without weakening product ownership."],toc:toc(scaleSections),sections:scaleSections,assessment:scaleAssessment,assessmentAfter:"specialist-pod-project",faq:[
 ["How should a fintech scale engineering after funding?","Map each workstream by how long the need lasts and how much ownership it carries. Keep core product and architecture ownership internal, hire permanently for long-term capability, and use specialists, pods or project teams for temporary, specialized or bounded work."],
 ["Should a startup hire permanently after raising capital?","For long-term core capabilities, yes. For temporary spikes, specialist gaps or defined projects, permanent hiring may add fixed cost and onboarding load before it adds delivery. Decide role by role."],
 ["What is an engineering pod?","A small cross-functional group—typically engineers with QA and delivery support—that takes on a continuing workstream under the client's product and technical leadership."],
 ["When should a fintech use external developers?","When the need is temporary, specialized or clearly bounded, or while permanent hiring catches up—provided internal leaders can direct and review the work."],
 ["What engineering roles should remain internal?","Product ownership, architecture governance, security accountability, engineering leadership and the people who hold deep domain knowledge of financial workflows."],
 ["How do you maintain product ownership with an external engineering team?","Keep repositories and access under company control, require internal code review and architecture oversight, make documentation part of done, agree IP terms and plan the handover from the start."],
],sources:[sources.dora,sources.topologies,sources.codeowners],finalEyebrow:"Scale delivery deliberately",finalHeadline:"Where is engineering capacity limiting your fintech roadmap?",finalBody:"Start with the workstream, skill gap or delivery constraint before deciding whether the answer is hiring, augmentation, a pod or a defined project team.",finalCta:"Review Your Engineering Capacity",related:[brokerage,a20,a21,capacity,fintech]};

const modern:BatchArticle={slug:"fintech-platform-modernization",cluster:"Fintech · Platform Modernization",title:"Fintech Platform Modernization: When Product Growth Starts Outrunning the Architecture",seoTitle:"Fintech Platform Modernization: When Architecture Limits Growth | Xyncwave",metaDescription:"How fintech leaders can tell when architecture, integrations or deployment are limiting product growth—and modernize the constraint without defaulting to a rewrite.",excerpt:"Read the six pressures on a growing fintech platform and modernize the part that is actually constraining the roadmap.",read:"18 min",published,modified:published,directQuestion:"When does a fintech platform need modernization?",directAnswer:"A fintech platform should be evaluated for modernization when architecture, deployment or integration constraints begin limiting required product change. The answer is not automatically a rebuild. Modernization may mean upgrading a runtime, refactoring a tangled area, extracting a service, putting providers behind a clear integration boundary, decoupling long-running work or improving observability. Identify which constraint is slowing the roadmap and change that, while preserving working business capability.",takeaways:["Product growth and architecture growth are different things.","More integrations increase platform coordination requirements.","Slow releases may reflect architecture, not headcount.","Full rewrites should require strong justification.","Observability is part of platform maturity.","Modernization should preserve working business capability where practical."],toc:toc(modernSections),sections:modernSections,assessment:modernAssessment,assessmentAfter:"modernize-constraint",faq:[
 ["What is fintech platform modernization?","Changing the architecture, runtime, integrations, delivery pipeline or operations of a fintech platform so it can support the changes the product now requires."],
 ["When should a fintech application be modernized?","When several pressures—product, integration, transaction, delivery, operational and data—converge and required changes become disproportionately expensive or risky."],
 ["Does modernization require a rewrite?","No. Most constraints can be addressed through upgrades, refactoring, service extraction or integration boundaries. A rewrite needs strong justification because of regression and transition risk."],
 ["When should fintech services become asynchronous?","When work is long-running, retriable, triggered by external status or not needed for the immediate customer response—with idempotency and visible failure handling in place."],
 ["How does observability support fintech reliability?","Logs, correlation IDs, audit trails, monitoring and alerts let teams trace a customer action across services and providers, diagnose incidents faster and release changes with more confidence."],
 ["Should integrations be separated behind middleware or APIs?","Often, as providers multiply. A boundary keeps provider-specific logic out of customer-facing code and makes providers easier to change, though a very small platform may not need one."],
],sources:[sources.strangler,sources.fsiLens,sources.sqs,sources.otel,sources.oidc,sources.dora],finalEyebrow:"Modernize the constraint",finalHeadline:"Which part of your fintech platform is making the roadmap harder to deliver?",finalBody:"Identify the architecture, integration, delivery or operational constraint first. Then decide whether it needs an upgrade, a refactor, a clearer boundary or a selected rebuild.",finalCta:"Review Your Fintech Platform",related:[brokerage,a19,a21,modernizationSolution,modernPillar]};

const integ:BatchArticle={slug:"fintech-api-integration-strategy",cluster:"Fintech · API & Integration",title:"Fintech API & Integration Strategy: Connecting Identity, Payments, Market Data, Trading and Reporting",seoTitle:"Fintech API & Integration Strategy: Building a Connected Platform | Xyncwave",metaDescription:"Design fintech integrations around state ownership, provider boundaries, idempotency, reconciliation and observability across identity, payments, data, trading and reporting.",excerpt:"Define what moves, who owns the state and what happens on failure before adding another point-to-point connection.",read:"19 min",published,modified:published,directQuestion:"What is a fintech API and integration strategy?",directAnswer:"A fintech integration strategy should define which systems participate in each customer workflow, which system owns each state, what data moves between them, how failures are handled and where provider-specific logic is contained. APIs are the mechanism; the strategy is the set of decisions about boundaries, reliability and reconciliation that keeps identity, payments, market data, trading and reporting consistent behind one customer experience.",takeaways:["APIs are mechanisms, not the integration strategy.","External-provider logic should be controlled behind stable platform boundaries.","Financial workflows need explicit state ownership.","Failure handling should be designed before production incidents occur.","Payments and trade workflows often require reconciliation.","Observability matters across the whole integration chain."],toc:toc(integrationSections),sections:integrationSections,assessment:integrationAssessment,assessmentAfter:"sync-async",faq:[
 ["What is fintech API integration?","Connecting a fintech platform with identity, payment, data, execution, document and reporting systems through APIs, events and pipelines, with defined state ownership and failure handling."],
 ["Why do fintech platforms use middleware?","To absorb provider differences, normalize data, centralize validation and monitoring, and keep customer-facing applications independent of external APIs."],
 ["How should payment integrations be designed?","Treat initiation, provider processing, response, internal state update, recording and reconciliation as separate steps, represent pending states honestly and make retries idempotent."],
 ["When should an integration be asynchronous?","When the work is long-running or retriable, when status arrives later by callback, or when it feeds reporting rather than the immediate customer response."],
 ["What is reconciliation in financial systems?","A routine comparison of expected, recorded and externally confirmed state that identifies missing, duplicate or mismatched records so they can be resolved."],
 ["How do you prevent duplicate processing?","Use stable request identifiers and idempotent operations so a repeated request has the same effect as the first, and check for existing records before creating new actions."],
 ["How should multiple financial-data providers be integrated?","Behind a provider abstraction that normalizes identifiers and formats, validates incoming data and exposes one consistent model to the rest of the platform."],
],sources:[sources.acl,sources.retry,sources.idempotency,sources.otel,sources.oidc,sources.fsiLens],finalEyebrow:"Connect the ecosystem deliberately",finalHeadline:"Which integration creates the greatest risk or friction in your fintech platform?",finalBody:"Map the workflow, state ownership, provider dependency and failure behaviour before adding another point-to-point connection.",finalCta:"Map Your Fintech Integrations",related:[brokerage,a19,a20,integrationSolution,integrationPillar]};

export const batchSevenArticles:BatchArticle[]=[scale,modern,integ];
