export const executiveDepth: Record<string, Record<string, string[]>> = {
  "ai-integration-readiness": {
    stack: [
      "Begin with a real decision or workflow, not a model demonstration. Name its owner, inputs, permitted actions, exception routes and acceptance criteria. A team cannot evaluate an AI-assisted process if it cannot explain what a correct human decision looks like or who handles a disputed output. Map the existing workflow before introducing automation: which steps require judgment, which are deterministic and which contain sensitive information? The result is a scope that can be governed and tested rather than an open-ended aspiration to 'add AI'.",
      "Readiness is layered. A plausible use case needs authoritative knowledge, a way to retrieve only permitted context, suitable tool interfaces, identity controls, human review where necessary and monitoring after launch. A strong model cannot repair a missing owner for an outdated policy or an API that grants broad administrative rights for a narrow task. Treat each layer as a question with a named answer. If one layer is absent, a limited advisory pilot may be sensible while action-taking automation is not.",
      "Define the unhappy path as carefully as the demonstration path. What happens when the answer is uncertain, the requested document is missing, a tool times out or a human reviewer disagrees? The workflow should state whether the system stops, asks for clarification or routes to a person. The ability to recover safely and explain the decision is part of readiness, not a post-launch enhancement."
    ],
    knowledge: [
      "A retrieval system needs more than a collection of documents. Record who owns each source, when it was last approved, what audience may see it and when it expires. A current policy and an obsolete procedure may contain similar phrases; without version and authority metadata, the wrong one can appear equally credible. Test ambiguous queries, contradictory records and customer-specific exceptions. When the answer cannot be grounded in permitted current material, the system should say so rather than fabricate a confident instruction.",
      "Apply access rules before content reaches the model. A user's permission to see one account should not become permission to search all customer records through a conversational interface. Scope retrieval by the user's identity and purpose, minimize sensitive fields and document retention for both prompts and outputs. Fine-tuning is not a substitute for access control. Include a procedure for removing a superseded document and checking that future responses no longer rely on it.",
      "Quality is partly an ownership question. If two departments maintain conflicting instructions, an AI system will expose that disagreement rather than solve it. Resolve the authoritative source and escalation path for each knowledge domain before increasing automation. Where decisions depend on changing business rules, involve the domain owner in reviewing test cases and subsequent updates."
    ],
    permissions: [
      "Separate read-only assistance from action-taking. Reading a permitted knowledge source carries a different risk from changing a record, sending a notification or initiating a refund. Define tool-level permissions for each action, validate arguments server-side and require approval for consequential steps. Limit rate and cost of tool calls so a loop cannot repeatedly act or consume unbounded resources. Prefer operations that can be previewed, confirmed and reversed where the underlying business process permits reversal; where reversal is impossible, increase review before execution.",
      "The action record should connect the user's request, retrieved context, proposed operation, authorization, tool response and final state. Protect sensitive content in those records and make access to them intentional. A human approval is meaningful only if the reviewer can see what will be done and on what basis. Do not treat a model's text as proof that a downstream system actually changed; verify the tool result and reconcile the resulting state.",
      "Prompt injection and misleading retrieved content are operational threats, not merely unusual prompts. An instruction inside an external document should not override tool permissions or the user's authorized task. Test attempts to request another account's data, bypass an approval step or repeat an action. The defense is layered: constrained tools, scoped identities, validation, review and monitoring. No single prompt can guarantee safe behavior."
    ],
    pilot: [
      "A useful pilot has a bounded task, representative examples and failure cases collected with the people who perform the work. Measure whether outputs are grounded, whether reviewers accept or correct them, how long review takes and what kinds of errors remain. Set stopping conditions for unacceptable responses or unauthorized actions. Keep evaluation data separate from live production information where feasible, and make clear which aspects of the pilot have not been tested in a production environment.",
      "Include the hidden labor in the result. If subject-matter experts spend more time checking and correcting a draft than they spent producing the original, the use case may need better source material, narrower scope or no automation. Review rejected outputs for patterns before changing models. A pilot should end with a decision: expand with controls, revise the workflow or stop. That decision is more valuable than a compelling demo with no path to ownership, monitoring and support."
    ]
  },
  "business-case-process-digitalization": {
    model: [
      "The Fragmentation Cost Model helps reveal costs that sit between systems rather than on a software invoice. Re-entry occurs when the same information is typed again. Reconciliation is the work of resolving contradictory records. Coordination is the time spent finding the right person or status. Visibility is the delay between an event and a reliable management view. Change cost is the effort of adapting a brittle workflow; scale cost appears when volume rises but the process cannot absorb it. Use these as categories for discovery, not as automatic monetary claims.",
      "Trace a representative item from initiation to decision. If a request moves from email to spreadsheet to an application and back to a report, note each handoff, owner, elapsed time and source of truth. The most expensive-looking step may not be the right starting point. A modest change that removes a recurring reconciliation loop could matter more than digitizing a form while preserving every downstream manual correction. Link the proposed intervention to the specific handoff it changes.",
      "Capacity released by a process change is not the same as cash saved. A business case should explain whether freed time is redeployed to more work, a service improvement or an avoided future hire. Do not translate every minute into a guaranteed financial return. Similarly, better visibility is valuable when it changes a named decision; a dashboard with no owner or action path is not a benefit merely because it exists."
    ],
    baseline: [
      "Observe the work as it occurs. A process map drawn in a meeting often omits exceptions, side spreadsheets and approvals handled through informal messages. Sample a variety of routine and exceptional cases, recording timestamps, corrections and people involved. Note what the current system measures reliably and what must be estimated. A baseline can be small but should be transparent: its period, sample, exclusions and uncertainty are more useful than a precise-looking number borrowed from another company.",
      "Distinguish elapsed time from labor time. A request waiting for approval may take days while requiring little active work; a manual reconciliation may take concentrated staff effort. Record both if the business decision depends on them. Also identify where errors surface: at data entry, during review or only at reporting time. If an intervention moves error detection earlier, show how that will be observed rather than assuming errors disappear.",
      "Do not inflate a case with hypothetical losses. If past incidents exist and the organization can verify their consequences, document them with context and appropriate review. Otherwise describe risk qualitatively and explain what evidence would allow it to be estimated. Finance, operations and technology owners should agree on definitions before results are used for approval."
    ],
    investment: [
      "Include the full cost of change: discovery, design, integration, data cleanup, training, support, parallel operation and ongoing ownership. A new workflow may briefly demand more effort while people learn it and historical records are migrated. The plan should say who supports users during that transition and when the old route can be retired. A procurement price alone does not show whether the organization can sustain the result.",
      "Integration can dominate the work. A new interface may depend on old identifiers, inconsistent statuses or access controlled by another team. Identify those dependencies before approving a broad rollout and budget a discovery step where uncertainty is high. State what is included, what remains a hypothesis and what would trigger a revised estimate. This makes the business case more credible than hiding unknown work in a single optimistic figure.",
      "Assign a process owner after launch. Someone must approve rule changes, maintain access, review exceptions and evaluate whether the workflow still supports the business. A digitalization investment without an operational owner can recreate the original fragmentation in a new tool."
    ],
    pilot: [
      "A pilot should test one important handoff from start to finish with the people who use it. Decide in advance what evidence supports expansion: fewer duplicate entries, a shorter wait for a specific approval, a clearer exception queue or a more reliable management status. Compare with the baseline using the same definitions. Record unintended effects, such as extra work for another team, as carefully as visible gains.",
      "Choose a pilot boundary that can be reversed or isolated if assumptions fail. Set a review date, a named decision-maker and the conditions for continuing, revising or stopping. If the intervention does not reduce the chosen friction, investigate whether the process rule, integration or adoption is the cause before buying more software. The point of a pilot is to improve the next decision, not to prove a preconceived return."
    ]
  },
  "operational-reporting-modernization": {
    chain: [
      "Start from a decision that depends on a report. Ask what the reader needs to decide, how current the information must be and which underlying event changes the answer. Then trace one measure back through the dashboard, business definition, transformation, validation and source record. Each undocumented export or spreadsheet adjustment is a place where traceability can be lost. Modernization repairs those boundaries so a reader can ask why a number changed and receive a reproducible explanation.",
      "Do not treat a dashboard redesign as a reporting-system redesign. A clearer chart may still display a measure assembled from contradictory source definitions. Put shared calculations in a governed modeling layer where changes can be reviewed, tested and versioned. Keep report-specific presentation choices separate from the canonical definition. The objective is not a single visual style; it is consistent meaning across teams and time.",
      "Capture identifiers and event time as information moves between systems. When a source corrects a historical record, the chain must show whether a report restates the earlier period or records the correction in the current period. Agree this behavior with the business owner. Without it, even a technically correct refresh can create a management dispute about what the report actually represents."
    ],
    sources: [
      "Make a source inventory at the field and owner level. For each critical measure, record which system owns the underlying event, how often it updates, what failures look like and whom to contact when a value changes unexpectedly. A sales system updated hourly and a finance system updated weekly cannot be joined as though both describe the same instant. Show an as-of time, choose an appropriate comparison window and tell readers where a figure is provisional.",
      "Set expectations for schema change. If a source team adds a new status or changes a field, downstream models need a review path rather than silently interpreting the new value as an old one. Tests can catch unknown statuses, null identifiers and missing batches. Named ownership turns those alerts into a resolution process. Data contracts can be lightweight, but they should specify the changes that consumers must know about.",
      "Manual corrections deserve a recorded workflow. If a user must amend a source value, capture who changed it, why, when and whether the source of authority also changed. An unexplained adjustment inside a report is not a substitute for fixing the underlying record."
    ],
    reliability: [
      "Test at more than one layer. Source checks establish whether records are present and plausible. Transformation checks verify relationships and definitions. Report checks catch unexpected shifts and stale refreshes. An alert must lead to a named owner, a way to inspect affected records and a decision about whether to publish with a warning or pause the report. A green pipeline indicator alone does not establish that the number is meaningful.",
      "Create a metric dictionary for decisions that matter. Define the measure, inclusion rules, exclusions, source, refresh cadence and owner. If engineering and finance use 'completed project' differently, document that distinction rather than forcing a misleading universal number. Agreement on definitions is a governance task supported by technical models, not something software can infer without the decision-makers.",
      "Monitor manual adjustment and cross-team reconciliation as diagnostic signals. If analysts repeatedly export and correct a particular figure, trace the recurring reason upstream. The target is not merely fewer spreadsheets; it is a report whose lineage and exceptions can be explained without rebuilding the calculation by hand every time."
    ],
    sequence: [
      "Modernize one vertical slice first: a source event, a defined transformation, validation, a report and the decision it supports. Choose a slice with a named owner and a meaningful pain point. Preserve a comparison with the existing report until differences can be explained. Then reuse the tested pattern for another measure or source. This sequence produces learning about governance and integrations before a large platform commitment.",
      "A warehouse may be justified when teams repeatedly need shared history and analysis across sources. It is not mandatory for every operational status view. A direct projection from a reliable source can be enough when one team needs a current state. Compare the decision cadence, number of sources, history requirements and support effort before selecting architecture. The Enterprise Reporting and Data Accuracy case study provides related solution context, not a promised performance or financial result for a different organization."
    ]
  }
};
