export const partnerDepth: Record<string, Record<string, string[]>> = {
  "white-label-software-development": {
    model: [
      "Frontstage and backstage are accountability boundaries, not secrecy for its own sake. The agency holds the customer relationship, shapes the brief and decides what it can promise. The engineering partner contributes to feasibility, architecture, implementation and testing. Shared governance is the mechanism that prevents those two views from separating: named decision owners, a regular review of scope and risks, and a clear route for resolving a request that changes technical assumptions. Without this interface, an agency can sell a feature the delivery team cannot safely support.",
      "Consider a customer requesting a reporting dashboard with data from several operational systems. The agency can own the experience, acceptance criteria and customer communication. A partner might implement ingestion, normalization and access controls. Before agreeing to a launch date, both parties need to establish who can supply source access, what a missing record means, how freshness is displayed and who signs off on a business definition. The model works when engineering findings reach the person making commitments to the customer in time to change them.",
      "Agree how the partner appears in customer-facing work. Some customers want direct technical discussions, while others want all communication through the agency. Either can work if the agency remains accountable and the partner can raise delivery risks without distortion. Record who writes estimates, who approves a change request and who communicates a delay. A white-label relationship should not make essential engineering context invisible to the people responsible for the outcome."
    ],
    comparisons: [
      "Staff augmentation typically gives an agency additional people under its own technical direction. White-label delivery can instead assign a bounded module or managed workstream to a partner that provides engineering leadership. A fixed project can be delivered under either model. The practical distinction is who decides the implementation approach, manages quality and carries the day-to-day coordination cost. Ask those questions in the statement of work rather than relying on the label of the service.",
      "An embedded engineer is useful when an agency already has architecture, reviews and delivery management but lacks a specific skill. A managed pod is more appropriate when it needs a team to coordinate a substantial workstream. Neither is a substitute for an agency's product judgment: the customer promise, priority and acceptance decision must remain visible. A quote that appears cheaper may shift hidden requirements management, QA or release effort back onto the agency; compare the full operating model, not only a rate card.",
      "Brand continuity should not obstruct operational transparency. If the end customer owns the software, clarify access, licenses, code provenance and support routes regardless of which team implements it. A model that prevents the customer from understanding their own assets creates a handover risk. The strongest arrangement lets the agency protect its relationship while maintaining enough technical traceability for future change."
    ],
    control: [
      "Repository and environment custody are practical tests of control. Prefer project-owned repositories and infrastructure accounts with named, scoped access for the partner. Decide who approves dependencies, handles secrets, reviews security-relevant changes and signs off on production releases. Record the treatment of pre-existing partner tools and third-party licenses with appropriate legal review. A statement about code ownership is not operationally sufficient if the agency cannot build, deploy or maintain what it paid for.",
      "Define quality before a milestone is due. A usable definition of done can include agreed acceptance examples, test coverage appropriate to risk, review of significant architectural decisions, deployment notes and known limitations. Review a vertical slice early so the agency can see both interface and engineering behavior before the whole workstream is complete. If an agency has no technical reviewer, it should arrange independent review of consequential design choices instead of treating a successful demo as proof of maintainability.",
      "Use a decision log for trade-offs that affect the customer: source-system assumptions, reporting definitions, data retention and integration failure behavior. Each record should explain what was chosen, the alternative and what would cause reassessment. This reduces the risk that a new engineer repeats a rejected approach or that the agency communicates an outdated assumption. The objective is a shared memory, not paperwork for its own sake."
    ],
    handover: [
      "Plan handover at the start. Inventory repositories, environments, service accounts, deployment steps, third-party dependencies and the people authorized to change each. Ask a team member other than the original implementer to run tests and deploy to a safe environment while the partner can still help. Use a representative failure scenario to check whether a support person can identify the issue, find its owner and restore service. If that is not possible, documentation is not yet complete.",
      "Continuity also means transferring rationale. Source code shows what was built, not why a data contract or service boundary was chosen. Provide decision records, a map of known limitations and a list of unresolved assumptions. Agree how defects discovered during the transition are handled and who communicates with the end customer. The published Engineering Capacity case study describes a delivery-capacity solution; it does not establish any undisclosed white-label contract or handover practice. Use it as related delivery context, not as a claim about a specific customer arrangement."
    ]
  },
  "evaluate-software-engineering-partner": {
    scorecard: [
      "A scorecard should help a buying team compare evidence, not turn nuanced judgment into a single unexplained number. Set non-negotiable requirements first, then score the partner's examples against your work. For architecture, ask for an anonymized decision record. For QA, ask how a failed acceptance test changes release plans. For delivery, ask who updates the estimate after a dependency changes. For communication, compare a sample status report and escalation path. Record both the answer and what was actually demonstrated.",
      "Evaluate timezone overlap as a working arrangement. Two hours of shared time with reliable written decisions can be more useful than a nominally local team that does not surface blockers. Ask when a design question receives a response, how a handoff is recorded and who can make a decision when a lead is unavailable. Escalation is similarly concrete: if a critical defect appears before a release, who can stop deployment, who investigates, who informs stakeholders and when is the plan revisited?",
      "Intellectual-property ownership, access, licensing and exit terms need direct review. Clarify who owns newly created work, what happens to any partner-owned starter kit, which third-party dependencies require separate licenses and whether the customer has the necessary rights to maintain the product. Legal terms should be checked by the appropriate professionals. The technical scorecard should still test practical custody: repositories, infrastructure accounts, build pipelines and documentation must be accessible to the organization responsible for the product."
    ],
    technical: [
      "A useful technical conversation presents a constraint rather than a trivia question. Suppose a provider API slows down intermittently. Ask the candidate how to distinguish a transient delay from an accepted but unfinished operation, when to retry and what the user should see. Listen for trade-offs around freshness, duplicate actions, observability and fallback behavior. A blanket answer such as 'add a cache' is insufficient until the candidate explains which data may safely be cached and how staleness will be indicated.",
      "An architecture critique can reveal whether a partner respects the existing system. Show a simplified current boundary with one known bottleneck, then ask for a sequence of low-risk changes and evidence that each helped. Strong reasoning includes an escape hatch if a hypothesis proves wrong. A proposal to replace everything without assessing migration, data ownership or operational interruption should prompt follow-up questions. The aim is not to find a partner who always chooses incremental change; it is to find one who can justify the size of change against the constraint.",
      "Check how engineers learn unfamiliar domain rules. In a short exercise, give a deliberately incomplete requirement and ask what they would need clarified before coding. Good questions might surface who owns the business definition, which errors are recoverable and what acceptance evidence will be used. This tests whether the partner can protect your team from ambiguous work rather than merely produce code quickly."
    ],
    governance: [
      "Request evidence of practice without demanding sensitive customer information. A redacted onboarding checklist can show how project access is granted; an offboarding process can show how it is revoked. A sample change record can show review and release discipline. Ask where secrets live and how production permissions are approved. Do not infer a certification or security guarantee from a polished presentation. Instead, determine which controls your project requires and who will verify them during delivery.",
      "Governance also covers the ordinary flow of decisions. Who owns the backlog? Who accepts a change in scope? Who resolves disagreement between product and architecture? How are incident responsibilities divided? Put these answers in an operating agreement and revisit them after the first real blocker. A partner that communicates a problem early with options may be more dependable than one that reports only completed tasks.",
      "Assess the exit path before signing. Ask for a sample handover inventory, an approach to knowledge transfer and terms for access to work in progress. The strongest answer is not an assurance that the relationship will never end; it is a practical way for another team to understand, build and operate the result if it does."
    ],
    pilot: [
      "Choose a pilot that crosses a real boundary: a small integration, a representative application change or one data workflow. Avoid a standalone demo that never touches your repository, review process or deployment environment. State what successful delivery includes beyond the feature: a decision record, tests, a short runbook and an acceptance walkthrough. Observe how the partner handles a missing permission or contradictory requirement, because those are ordinary delivery conditions rather than unusual stress tests.",
      "At the end, ask an internal engineer to run the work without the partner guiding each step. If that fails, identify whether the gap is access, documentation, environment setup or hidden product knowledge. Evaluate the pilot against the scorecard and against the true coordination effort it required from your team. A fast implementation that consumes disproportionate internal review time may be the wrong partnership model, even when the code itself is usable."
    ]
  },
  "reduce-engineering-backlog": {
    causes: [
      "Begin by separating demand from capacity. Count the work entering the system, the work completed and the age of unresolved items over a meaningful period. A long list is not automatically a capacity problem: it might contain requests nobody has decided to reject, blocked items waiting for another team or defects repeatedly reopened after release. Tag a sample of old items by the reason they did not move. The pattern gives a more useful first intervention than simply hiring for a large number on a board.",
      "Architecture can be a hidden constraint. If a change to billing requires extensive regression checks across an unrelated customer workflow, another developer may increase coordination without increasing completed value. A dependency can be organizational too: a frontend change may wait for a backend API owned by a team with a different roadmap. Diagnose whether the right response is clearer interfaces, targeted testability work, cross-skilling or dedicated ownership of a blocked boundary.",
      "Distinguish short-lived demand from a persistent capability gap. A temporary migration may need a bounded team. Repeated delays around data pipelines or deployment suggest a capability the organization must sustain. In either case, keep the product decision and acceptance owner named; additional hands cannot resolve ambiguous priorities."
    ],
    flow: [
      "Map where a representative work item waits: intake, clarification, design, development, review, QA, deployment or external approval. Measure elapsed time at each boundary rather than equating the number of open pull requests with productivity. If most delay is in review, hiring more implementers simply enlarges that queue. Put a limit on work in progress and agree what happens when a blocked item consumes a slot. The aim is to finish valuable work, not to maximize simultaneous starts.",
      "Protect intake. Every requested feature carries a cost of triage, clarification and later re-evaluation. Give a product owner the authority to decline or defer work that does not meet the current priority. Keep a route for urgent incidents, but define what qualifies as urgent and what gets displaced when it arrives. Otherwise a nominal roadmap is repeatedly interrupted by unmeasured commitments, and the backlog ceases to describe what the team will actually deliver.",
      "Review aging work for hidden rework. A ticket may move between 'done' and 'in progress' because its acceptance criteria never included a provider failure or a business exception. The remedy is a smaller testable slice and an early conversation between product, engineering and QA. Flow improves when uncertainty is resolved before implementation, not just when people type faster."
    ],
    constraints: [
      "If QA is the queue, make changes easier to test. Begin with the scenarios that are repeated on every release, then decide which can become automated checks and which require human judgment. Identify unstable environments and test data that cause false failures. A new QA hire can help, but a permanently slow manual regression path may continue to limit throughput unless the product becomes more testable.",
      "If requirements are the queue, look at how often work returns for clarification after coding begins. Ask whether the request specifies expected behavior for an exception, the owner of a business rule and what evidence demonstrates completion. A short discovery session can produce a small acceptance example that saves repeated rework. This is not a demand for exhaustive specifications; it is an attempt to expose the decisions that are genuinely missing.",
      "If release is the queue, establish who can approve a deployment and what prevents the team from doing it safely. A missing rollback path, shared environment or manual credential exchange can dominate the schedule regardless of implementation capacity. Fix the boundary with the highest wait time first, then measure whether throughput changes before adding more people."
    ],
    model: [
      "A specialist is appropriate when a specific capability blocks an otherwise functioning team, such as deployment automation or data modeling. A bounded project team works when the outcome and acceptance are defined. An embedded pod fits an evolving workstream that needs sustained context. Internal reprioritization may be best when too many priorities compete for the same team. Choose based on the duration and shape of the constraint, not on the fastest available staffing proposal.",
      "Set a learning objective for any external capacity. The partner should leave tests, documentation, decision records and a repeatable operating path, not just a smaller ticket count. Define who reviews work, who owns priorities and which team handles support after delivery. The Engineering Capacity case study is related context for extending delivery capability; it is not evidence that a particular capacity model will reduce another company's backlog by a predicted amount."
    ]
  }
};
