// Final operational checkpoints: concrete actions and counterexamples, not invented client outcomes.
export const decisionDepth: Record<string, Record<string, string[]>> = {
 "fintech-what-to-outsource":{model:[
 "There is no universal list of technologies that must remain internal. A payment provider integration can be strategically significant when it determines the product's customer promise, while a complex internal reporting migration may be suitable for a bounded external team if its definitions and acceptance are clear. Test the actual decision rights: who may change the contract with the provider, who decides what a failed response means to the customer and who owns the resulting support obligation? Those answers determine the right operating model more reliably than whether the code is called frontend or backend.",
 "A useful procurement brief has three layers. First, state the business constraint and the domain decisions already made. Second, list the decisions the partner may propose but not approve alone. Third, define how delivery will be checked, including failure cases and handover. This gives a prospective partner enough context to challenge weak assumptions without silently assuming strategic authority. Ask candidates to identify what they cannot estimate yet; honest uncertainty is more useful than an estimate built around an undefined customer state."
 ],proof:[
 "When reviewing a case study, separate published capabilities from the operating arrangement behind them. Connected onboarding, payment and reporting modules show the kinds of boundaries that must be designed, but they do not reveal which party owned each decision or what contract governed delivery. Ask a provider for a responsibility map relevant to your product rather than inferring one from a solution narrative. The map should survive staff turnover: a new internal lead must be able to locate the rationale, tests and owners for a consequential change."
 ]},
 "fintech-asynchronous-workflows":{flow:[
 "Document state transitions in a table before choosing infrastructure. For each transition, specify the current state, required event, action to persist, external dependency and possible next states. Add an explicit branch for unknown outcomes. A timeout from a provider is not automatically a rejection; an accepted operation may simply lack its acknowledgement. A transition table lets engineers write tests for late events and lets operations decide when to investigate. It also prevents the interface from treating a queue acknowledgement as final completion.",
 "Make the correlation reference available through the whole journey. The reference should connect a customer request to processing attempts, provider acknowledgements and support investigation, while not exposing secrets in logs or customer-facing URLs. When a transaction is resubmitted after a browser refresh, the platform can locate the existing intent rather than generate a second one. The exact storage and expiry design depend on the business action and provider behavior; what matters is preserving identity across retries and recovery."
 ],failure:[
 "Run failure-injection exercises in a non-production setting. Stop a worker after a provider accepts an action but before the local result is recorded; delay a callback; send the same event twice; change their order. For each, write down the expected state, whether the worker may retry and what an operator sees. If the team cannot agree, there is a business-rule gap, not merely a missing retry library. A test that catches this disagreement before launch is itself a useful architectural outcome."
 ]},
 "fintech-data-engineering":{chain:[
 "For every published metric, make a compact contract: name, business meaning, source owner, input fields, effective time, exclusions, update cadence and correction policy. The contract helps distinguish a real change in the business from a change in calculation. A metric may be technically reproducible yet still unsuitable for a board report if a source can silently revise prior periods. Ask report users whether they need the latest corrected view or the view that was available at a particular decision date. The architecture must preserve whichever history the decision requires.",
 "Avoid placing all reconciliation logic at the end of the pipeline. Check identifiers and event validity near ingestion, relationships during transformation and business consistency before a metric is published. When a check fails, retain the offending record and reason in an appropriately protected exception path. Simply discarding a row can make the report look clean while hiding the precise discrepancy a finance or operations team needs to review. The exception path is part of the information product."
 ],sources:[
 "Evaluate source changes as product changes. If a provider adds a new status, ask whether it represents a new business state or a synonym for an existing one. Do not map it automatically to 'other' in a management report if that obscures a consequential event. A schema test can alert the data team, but a domain owner must decide what the status means. Record that decision and reprocess affected history when appropriate. This is how data ownership connects engineering work with the business interpretation of a report.",
 "Where data is sensitive, use the least detailed representation that still supports the decision. A leadership trend might need counts by period and channel, not identity documents or full account records. Keep raw access, derived models and published measures separately governed. Review who can see exception records, because those may contain more detail than the final dashboard. Data minimization and reproducibility are not opposites: a controlled lineage path can explain a measure without broadly distributing the underlying personal information."
 ],reconcile:[
 "Use a small sample of exceptions to design the operational response. One row may be missing from a provider file, another may arrive late and a third may have a conflicting state. Each requires a different action: wait for the expected file, rerun ingestion or investigate the business record. Define the owner and safe correction path for each category. When the same category recurs, repair the source contract or transformation rather than normalizing manual correction as permanent routine work."
 ],models:[
 "A modeling decision should include costs of maintenance and explanation. A real-time analytical pipeline may add streaming state, monitoring and correction complexity even if the management question is reviewed weekly. Conversely, a daily batch may be inadequate for an operational exception queue. Build a thin prototype using representative history and ask decision-makers to interpret it. If two teams still disagree about what the measure counts, postpone expensive infrastructure choices until the definition is resolved.",
 "Use lineage as a test of trust, not only as a technical diagram. Select a reported figure, locate its transformation and trace several contributing source records. Then introduce a correction and verify whether the figure changes in the expected period with a visible explanation. If that test fails, more dashboard features will not fix the underlying decision problem. The next investment may be source instrumentation, validation or a reconciliation workflow rather than a larger warehouse."
 ]},
 "white-label-software-development":{control:[
 "Use a change scenario to test the partnership agreement. The customer asks for a new data source halfway through a dashboard project. Who assesses the source quality? Who explains how this affects the original schedule and definition of done? Who may authorize a revised scope? If the partner raises a technical constraint, the agency must have a channel to bring it to the customer accurately. If the agency makes a new commitment, the partner must know before implementation begins. This shared change path protects the customer relationship more than concealing every technical discussion.",
 "Review commercial and technical boundaries together. A managed workstream may include QA and release notes, or those tasks may remain with the agency. State which is true. Assign an owner for defects discovered after acceptance and for dependencies that fail outside the partner's code. Without that clarity, each side can reasonably believe the other handles support. The aim is not to transfer all risk to one party; it is to make the handoff observable and fair."
 ],comparisons:[
 "Choose augmentation when you can already direct engineers and need a defined capability within that system. Choose managed white-label work when the partner should own engineering coordination for a separable outcome. A hybrid is possible, but keep the boundaries legible. Ask what happens if the agency's lead is unavailable for a week: can the partner proceed within agreed decisions, or must all work stop? The answer reveals whether autonomy matches the work and governance."
 ]},
 "evaluate-software-engineering-partner":{scorecard:[
 "Score unknowns separately from weaknesses. A partner that cannot share another client's private code should not be marked as technically weak; invite a bounded exercise or redacted artifact. Equally, an unsupported claim that 'security is built in' should remain unverified until the team shows an appropriate practice. Document confidence and source of evidence for each dimension. This keeps a polished pitch from receiving the same weight as a demonstrated review, recovery or handover process.",
 "Bring multiple functions into the evaluation at the right point. Engineering can assess technical trade-offs, product can assess clarification and decision ownership, security can assess access, and procurement or counsel can evaluate terms. Do not ask one evaluator to certify disciplines outside their remit. Resolve non-negotiable gaps before comparing optional strengths. A partner with excellent architecture reasoning but unacceptable asset custody may be unsuitable for a sensitive workstream even if its overall numerical score looks high."
 ],governance:[
 "Check replacement and continuity with a practical question: if a principal engineer becomes unavailable next week, who can explain the architecture, access the work and continue an in-flight change? Look for shared notes, reviewed code and an actual handover process. The answer will vary by engagement size, but a single indispensable person is a visible risk. Agree what advance notice, replacement review and knowledge transfer are required before the team depends on that role."
 ]},
 "reduce-engineering-backlog":{flow:[
 "Measure flow without turning it into a productivity contest. Cycle time can reveal waiting, but comparing individual developers by tickets completed rewards small easy tasks and ignores architectural or support work. Review a distribution of work types and inspect outliers with the team. An old item may be a deliberately paused option; another may be a customer-critical defect blocked by a missing decision. The same age requires different action depending on value, risk and ownership.",
 "Introduce work-in-progress limits experimentally. Set a cap for one stage, agree how blockers are flagged and revisit whether completed work moves faster. If urgent work repeatedly bypasses the cap, investigate the source of interruptions rather than blaming the team for not following process. Preserve capacity for operational incidents where appropriate. A flow rule should help the team see constraints, not hide legitimate demand in an unofficial queue."
 ],constraints:[
 "When a dependency is external, make its service expectations explicit. Which input must your team provide, who approves changes, what response time is realistic and how are disagreements escalated? A vague statement that another team is 'blocking us' cannot support a useful decision. A small contract or shared planning session may remove more delay than a new engineering pod. If the dependency cannot be changed, plan around it honestly and avoid starting work that will predictably sit unfinished."
 ]},
 "ai-integration-readiness":{permissions:[
 "Review tool interfaces from the perspective of least privilege. An API that exposes a broad update operation may be convenient for a human administrator but unsuitable for an assistant carrying out one narrow task. Create constrained operations with validated parameters and task-specific access rather than relying on a natural-language instruction not to misuse a powerful endpoint. Consider rate limits and execution budgets, and define whether a failed call can be retried without a duplicate effect. If an action cannot be reversed, make that limitation visible at the review point.",
 "An audit trail should explain what happened without becoming an unrestricted copy of sensitive prompts and records. Set retention, redaction and access appropriate to the information involved. Link the human approval to the exact action approved; a broad approval of a conversation is not necessarily approval of every later tool call. Test whether an operator can distinguish a model suggestion, a human confirmation and a verified change in the target system."
 ],stack:[
 "A readiness workshop can rank use cases by consequence and controllability. A read-only internal summary based on governed documents is a different starting point from automated changes to financial or medical records. For each candidate, ask whether an incorrect output can be noticed before it causes harm, whether a human can correct it and whether the underlying information can be verified. This helps teams choose a sensible first pilot without pretending that every use case shares the same safety threshold."
 ]},
 "business-case-process-digitalization":{baseline:[
 "Show the baseline as a range when the sample is small or work varies widely. If one exceptional request takes far longer than routine requests, present both instead of averaging away the distinction. Explain which step consumes human effort and which step is waiting for a decision. Gather input from people doing the work, not only their managers; they often know which side spreadsheet or informal approval actually makes the process function. Use those findings to refine the proposed scope before estimating benefits."
 ],investment:[
 "Compare a minimum useful change with a broader platform plan. A narrow integration may solve the immediate handoff, while a larger rebuild may address several related processes but require more adoption work. Document what each option leaves unresolved, the dependencies it creates and how it will be operated. A 'do nothing yet' option can also be reasonable if the baseline shows little consequence or the process is about to change for other reasons. Decision quality improves when the alternatives are explicit."
 ],model:[
 "Make benefits conditional on adoption. A system can create an authoritative status, but if teams continue updating the old spreadsheet, reconciliation may grow rather than shrink. The business case should state who changes behavior, how old routes are retired and what evidence shows the new record is actually used. Treat adoption as work with owners and support, not as an automatic effect of installing software."
 ]},
 "operational-reporting-modernization":{reliability:[
 "Establish a response to disagreement before it happens. When a new report differs from an old one, classify whether the cause is timing, definition, missing records, transformation or manual adjustment. Give each category a person who can resolve it and an explanation a report consumer can understand. Do not force a new output to equal the old number if the old process contained an error; equally, do not declare the new pipeline correct just because it ran successfully. Reconciliation is a review of evidence, not a cosmetic match."
 ],sources:[
 "Consider how upstream teams will learn that a reporting field matters. A developer renaming a status might see an application refactor, while a data team sees a broken management measure. Record critical data consumers and notify them of consequential source changes. This can be as simple as a reviewed contract and automated detection of unknown values. The important property is a visible path from upstream change to downstream decision owner."
 ],chain:[
 "During discovery, ask a manager what action would change if the disputed measure were more reliable. If there is no clear action, the project may be optimizing an attractive report rather than an important decision. If the action is time-sensitive, prioritize freshness and exception routing. If it is periodic strategic planning, prioritize stable definitions and reproducible history. The reporting architecture should reflect the decision's actual cadence and consequence."
 ]}
};

export const finalNotes: Record<string, string[]> = {
 "white-label-software-development": ["Before kickoff, run a joint discovery on one ambiguous customer request. Ask the agency to state the desired customer outcome and the engineering partner to list the assumptions needed to implement it. Turn disagreements into decisions with owners rather than hiding them in an estimate. Repeat when the brief changes; a shared view of uncertainty is the central operating discipline of a successful white-label arrangement."],
 "reduce-engineering-backlog": ["At the next planning review, ask which work has a named outcome and acceptance owner, which is waiting on an external dependency and which no longer justifies attention. Close or defer the last category explicitly. Then compare completed value and time spent waiting in the next cycle. This small experiment tests whether governance and flow, rather than raw headcount, are responsible for the accumulated queue.", "If added capacity remains the answer, specify the first independently deliverable slice, the reviewer and the handover. A team with no ready work package cannot use an extra engineer productively on day one. Preparing that interface is a valuable part of the intervention, not unnecessary overhead."],
 "ai-integration-readiness": ["Invite the workflow owner and a person who handles exceptions to review the pilot cases together. Their disagreements may expose undocumented policy or contradictory source material before a model is involved. Record which questions remain unresolved, who may settle them and how updates reach the deployed workflow. That preparation makes evaluation repeatable as the system and business rules change."],
 "business-case-process-digitalization": ["Show decision-makers a simple evidence register next to each expected benefit: baseline observation, proposed change, measurement method and owner. Where an expected effect cannot yet be measured, label it an assumption and test it in the pilot. The register makes a proposed investment defensible without pretending to know a future ROI, and it gives the implementation team a clear basis for choosing which friction to remove first.", "Review the case again after adoption, not only after launch. A feature can be delivered on schedule while manual handoffs persist outside it. Interview users and inspect a few real records to confirm that the intended process changed. If not, adjust training, ownership or integration before claiming the original benefit was realized."],
 "operational-reporting-modernization": ["At the end of each vertical slice, write a short operating agreement: who owns the source, who maintains the transformation, who reviews exceptions, when the report refreshes and how a definition change is approved. Revisit it when a new source or decision is added. The agreement keeps the reporting chain trustworthy after the initial engineering project, when undocumented assumptions would otherwise return.", "Ask report users to identify the uncertainty they can now resolve, and the uncertainty that remains. A reliable report can still be limited by missing source history or a decision that uses an ambiguous definition. Stating those limits visibly is more useful than presenting a precise number whose provenance cannot be explained."]
};
