/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiOpportunityAssessmentRouteImport } from './routes/ai-opportunity-assessment'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DigitalizationAssessmentRouteImport } from './routes/digitalization-assessment'
import { Route as EngineeringCapacityAssessmentRouteImport } from './routes/engineering-capacity-assessment'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as StartAConversationRouteImport } from './routes/start-a-conversation'
import { Route as TechnologyPartnershipRouteImport } from './routes/technology-partnership'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WhyXyncwaveRouteImport } from './routes/why-xyncwave'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as CaseStudiesEngineeringCapacityRouteImport } from './routes/case-studies.engineering-capacity'
import { Route as CaseStudiesTrackTraceRouteImport } from './routes/case-studies.track-trace'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as LpSlugRouteImport } from './routes/lp.$slug'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'
import { Route as ThankYouTypeRouteImport } from './routes/thank-you.$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiOpportunityAssessmentRoute = AiOpportunityAssessmentRouteImport.update({
  id: '/ai-opportunity-assessment',
  path: '/ai-opportunity-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalizationAssessmentRoute =
  DigitalizationAssessmentRouteImport.update({
    id: '/digitalization-assessment',
    path: '/digitalization-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const EngineeringCapacityAssessmentRoute =
  EngineeringCapacityAssessmentRouteImport.update({
    id: '/engineering-capacity-assessment',
    path: '/engineering-capacity-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const StartAConversationRoute = StartAConversationRouteImport.update({
  id: '/start-a-conversation',
  path: '/start-a-conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyPartnershipRoute = TechnologyPartnershipRouteImport.update({
  id: '/technology-partnership',
  path: '/technology-partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyXyncwaveRoute = WhyXyncwaveRouteImport.update({
  id: '/why-xyncwave',
  path: '/why-xyncwave',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesEngineeringCapacityRoute =
  CaseStudiesEngineeringCapacityRouteImport.update({
    id: '/engineering-capacity',
    path: '/engineering-capacity',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesTrackTraceRoute = CaseStudiesTrackTraceRouteImport.update({
  id: '/track-trace',
  path: '/track-trace',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IndustriesRoute,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const LpSlugRoute = LpSlugRouteImport.update({
  id: '/lp/$slug',
  path: '/lp/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SolutionsRoute,
} as any)
const ThankYouTypeRoute = ThankYouTypeRouteImport.update({
  id: '/thank-you/$type',
  path: '/thank-you/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-opportunity-assessment': typeof AiOpportunityAssessmentRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/digitalization-assessment': typeof DigitalizationAssessmentRoute
  '/engineering-capacity-assessment': typeof EngineeringCapacityAssessmentRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/start-a-conversation': typeof StartAConversationRoute
  '/technology-partnership': typeof TechnologyPartnershipRoute
  '/terms': typeof TermsRoute
  '/why-xyncwave': typeof WhyXyncwaveRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/engineering-capacity': typeof CaseStudiesEngineeringCapacityRoute
  '/case-studies/track-trace': typeof CaseStudiesTrackTraceRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/lp/$slug': typeof LpSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/thank-you/$type': typeof ThankYouTypeRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-opportunity-assessment': typeof AiOpportunityAssessmentRoute
  '/contact': typeof ContactRoute
  '/digitalization-assessment': typeof DigitalizationAssessmentRoute
  '/engineering-capacity-assessment': typeof EngineeringCapacityAssessmentRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-a-conversation': typeof StartAConversationRoute
  '/technology-partnership': typeof TechnologyPartnershipRoute
  '/terms': typeof TermsRoute
  '/why-xyncwave': typeof WhyXyncwaveRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/engineering-capacity': typeof CaseStudiesEngineeringCapacityRoute
  '/case-studies/track-trace': typeof CaseStudiesTrackTraceRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/lp/$slug': typeof LpSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/thank-you/$type': typeof ThankYouTypeRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-opportunity-assessment': typeof AiOpportunityAssessmentRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/digitalization-assessment': typeof DigitalizationAssessmentRoute
  '/engineering-capacity-assessment': typeof EngineeringCapacityAssessmentRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/start-a-conversation': typeof StartAConversationRoute
  '/technology-partnership': typeof TechnologyPartnershipRoute
  '/terms': typeof TermsRoute
  '/why-xyncwave': typeof WhyXyncwaveRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/engineering-capacity': typeof CaseStudiesEngineeringCapacityRoute
  '/case-studies/track-trace': typeof CaseStudiesTrackTraceRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/lp/$slug': typeof LpSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/thank-you/$type': typeof ThankYouTypeRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-opportunity-assessment'
    | '/case-studies'
    | '/contact'
    | '/digitalization-assessment'
    | '/engineering-capacity-assessment'
    | '/industries'
    | '/insights'
    | '/privacy'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/solutions'
    | '/start-a-conversation'
    | '/technology-partnership'
    | '/terms'
    | '/why-xyncwave'
    | '/case-studies/$slug'
    | '/case-studies/engineering-capacity'
    | '/case-studies/track-trace'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/lp/$slug'
    | '/solutions/$slug'
    | '/thank-you/$type'
    | '/case-studies/'
    | '/industries/'
    | '/insights/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-opportunity-assessment'
    | '/contact'
    | '/digitalization-assessment'
    | '/engineering-capacity-assessment'
    | '/privacy'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/start-a-conversation'
    | '/technology-partnership'
    | '/terms'
    | '/why-xyncwave'
    | '/case-studies/$slug'
    | '/case-studies/engineering-capacity'
    | '/case-studies/track-trace'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/lp/$slug'
    | '/solutions/$slug'
    | '/thank-you/$type'
    | '/case-studies'
    | '/industries'
    | '/insights'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-opportunity-assessment'
    | '/case-studies'
    | '/contact'
    | '/digitalization-assessment'
    | '/engineering-capacity-assessment'
    | '/industries'
    | '/insights'
    | '/privacy'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/solutions'
    | '/start-a-conversation'
    | '/technology-partnership'
    | '/terms'
    | '/why-xyncwave'
    | '/case-studies/$slug'
    | '/case-studies/engineering-capacity'
    | '/case-studies/track-trace'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/lp/$slug'
    | '/solutions/$slug'
    | '/thank-you/$type'
    | '/case-studies/'
    | '/industries/'
    | '/insights/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiOpportunityAssessmentRoute: typeof AiOpportunityAssessmentRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DigitalizationAssessmentRoute: typeof DigitalizationAssessmentRoute
  EngineeringCapacityAssessmentRoute: typeof EngineeringCapacityAssessmentRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  InsightsRoute: typeof InsightsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  StartAConversationRoute: typeof StartAConversationRoute
  TechnologyPartnershipRoute: typeof TechnologyPartnershipRoute
  TermsRoute: typeof TermsRoute
  WhyXyncwaveRoute: typeof WhyXyncwaveRoute
  LpSlugRoute: typeof LpSlugRoute
  ThankYouTypeRoute: typeof ThankYouTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-opportunity-assessment': {
      id: '/ai-opportunity-assessment'
      path: '/ai-opportunity-assessment'
      fullPath: '/ai-opportunity-assessment'
      preLoaderRoute: typeof AiOpportunityAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digitalization-assessment': {
      id: '/digitalization-assessment'
      path: '/digitalization-assessment'
      fullPath: '/digitalization-assessment'
      preLoaderRoute: typeof DigitalizationAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering-capacity-assessment': {
      id: '/engineering-capacity-assessment'
      path: '/engineering-capacity-assessment'
      fullPath: '/engineering-capacity-assessment'
      preLoaderRoute: typeof EngineeringCapacityAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-a-conversation': {
      id: '/start-a-conversation'
      path: '/start-a-conversation'
      fullPath: '/start-a-conversation'
      preLoaderRoute: typeof StartAConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology-partnership': {
      id: '/technology-partnership'
      path: '/technology-partnership'
      fullPath: '/technology-partnership'
      preLoaderRoute: typeof TechnologyPartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-xyncwave': {
      id: '/why-xyncwave'
      path: '/why-xyncwave'
      fullPath: '/why-xyncwave'
      preLoaderRoute: typeof WhyXyncwaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/engineering-capacity': {
      id: '/case-studies/engineering-capacity'
      path: '/engineering-capacity'
      fullPath: '/case-studies/engineering-capacity'
      preLoaderRoute: typeof CaseStudiesEngineeringCapacityRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/track-trace': {
      id: '/case-studies/track-trace'
      path: '/track-trace'
      fullPath: '/case-studies/track-trace'
      preLoaderRoute: typeof CaseStudiesTrackTraceRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/industries/': {
      id: '/industries/'
      path: '/'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/lp/$slug': {
      id: '/lp/$slug'
      path: '/lp/$slug'
      fullPath: '/lp/$slug'
      preLoaderRoute: typeof LpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/thank-you/$type': {
      id: '/thank-you/$type'
      path: '/thank-you/$type'
      fullPath: '/thank-you/$type'
      preLoaderRoute: typeof ThankYouTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  CaseStudiesEngineeringCapacityRoute: typeof CaseStudiesEngineeringCapacityRoute
  CaseStudiesTrackTraceRoute: typeof CaseStudiesTrackTraceRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  CaseStudiesEngineeringCapacityRoute: CaseStudiesEngineeringCapacityRoute,
  CaseStudiesTrackTraceRoute: CaseStudiesTrackTraceRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

interface IndustriesRouteChildren {
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesSlugRoute: IndustriesSlugRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSlugRoute: SolutionsSlugRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiOpportunityAssessmentRoute: AiOpportunityAssessmentRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ContactRoute: ContactRoute,
  DigitalizationAssessmentRoute: DigitalizationAssessmentRoute,
  EngineeringCapacityAssessmentRoute: EngineeringCapacityAssessmentRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  InsightsRoute: InsightsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  StartAConversationRoute: StartAConversationRoute,
  TechnologyPartnershipRoute: TechnologyPartnershipRoute,
  TermsRoute: TermsRoute,
  WhyXyncwaveRoute: WhyXyncwaveRoute,
  LpSlugRoute: LpSlugRoute,
  ThankYouTypeRoute: ThankYouTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
